export interface BlogPost {
  slug: string;
  title: string;
  description: string;
  toolSlug: string;
  date: string;
  keywords: string[];
  sections: { heading: string; content: string }[];
}

export const blogPosts: BlogPost[] = [
  {
    slug: "yarn-calculator-guide",
    title: "How Much Yarn Do I Need? The Complete Guide to Calculating Yarn for Any Project",
    description: "Learn how to calculate exactly how much yarn you need for blankets, sweaters, scarves, and more. Includes yardage charts by project type and yarn weight.",
    toolSlug: "yarn-calculator",
    date: "2026-02-01",
    keywords: ["how much yarn do I need", "yarn yardage calculator", "yarn for blanket", "yarn for sweater", "calculate yarn needed", "yarn estimation guide"],
    sections: [
      { heading: "Why Yarn Estimation Matters", content: "Running out of yarn mid-project is every crafter's nightmare. Different dye lots can create visible color shifts in your finished piece, and buying too much wastes money. The good news is that estimating yarn is straightforward once you understand the variables: project size, yarn weight, and stitch pattern.\n\nThe three factors that determine yarn usage are surface area (how big is the project), yarn weight (thicker yarn covers more area per yard but also weighs more per yard), and stitch pattern (cables and brioche eat significantly more yarn than stockinette or single crochet)." },
      { heading: "Yardage by Project Type", content: "Here are general yardage ranges for worsted weight yarn (#4):\n\nScarves typically need 200\u2013400 yards. A standard 6-inch-wide, 60-inch-long scarf in stockinette takes about 250 yards. Cable or brioche scarves need 300\u2013400.\n\nHats need 150\u2013250 yards for adults, 80\u2013150 for children. Bulky yarn hats use less yardage but more weight.\n\nBaby blankets (36\u00D752 inches) need 900\u20131,400 yards. Throw blankets (50\u00D760 inches) need 1,200\u20132,000 yards. Queen bed blankets can require 3,000\u20134,500 yards.\n\nAdult sweaters range from 1,000\u20131,800 yards depending on size and design. Cardigans need 200\u2013400 yards more than pullovers. Socks typically need 350\u2013450 yards per pair." },
      { heading: "How Yarn Weight Affects Yardage", content: "Thinner yarn needs more yardage to cover the same area because each stitch is smaller. A throw blanket in fingering weight might need 3,000+ yards, while the same blanket in super bulky needs only 600\u2013800 yards.\n\nHowever, thinner yarn has more yards per skein (a fingering weight skein might have 400+ yards vs. 100 yards for super bulky), so the number of skeins doesn't always increase proportionally.\n\nThe trade-off is time: a fingering weight blanket takes significantly longer to knit or crochet than a super bulky one." },
      { heading: "Stitch Pattern Multipliers", content: "Not all stitches use the same amount of yarn. Here's how common patterns compare to basic stockinette/single crochet:\n\nStockinette and single crochet are the baseline (1x). Garter stitch and half double crochet use about the same. Seed stitch and moss stitch use about 5% more.\n\nRibbing uses 5\u201310% more because the fabric compresses horizontally. Cables use 20\u201330% more because each cable crossing pulls extra yarn to the front. Brioche and fisherman's rib use 40\u201350% more because you're essentially knitting every row twice. Lace typically uses 10\u201315% less because of the yarn-over holes." },
      { heading: "The Golden Rule: Always Buy Extra", content: "Even with a perfect calculation, buy one extra skein from the same dye lot. Yarn from different dye lots \u2014 even the same color number \u2014 can have subtle shade differences that become visible in your finished piece.\n\nMost yarn shops will let you return unused skeins within a reasonable timeframe, so there's no downside to buying one extra.\n\nOur Yarn Yardage Calculator handles all of these variables automatically. Enter your project type, dimensions, yarn weight, and stitch pattern, and it calculates exact yardage with a 10% safety buffer built in." },
    ],
  },
  {
    slug: "needle-size-chart-guide",
    title: "Knitting Needle & Crochet Hook Size Chart \u2014 US, Metric, UK & Japanese Sizes",
    description: "The complete knitting needle and crochet hook size conversion chart. Convert between US, metric (mm), UK, and Japanese sizing systems instantly.",
    toolSlug: "needle-converter",
    date: "2026-02-01",
    keywords: ["knitting needle sizes", "crochet hook sizes", "needle size chart", "US to metric needle conversion", "UK needle sizes", "Japanese knitting needles"],
    sections: [
      { heading: "Why Needle Sizes Are Confusing", content: "Knitting needle and crochet hook sizing is confusing because four different systems exist simultaneously: US sizes (numbers and letters), metric (millimeters), UK sizes (numbers that run backwards compared to US), and Japanese sizes (their own numbering system).\n\nThe US system is the most common in North American patterns. Metric is universal and used in most modern patterns worldwide. UK sizes are found in older British patterns and some Australian ones. Japanese sizes appear in Japanese knitting books, which have become popular globally.\n\nThe core problem is that US and UK numbering goes in opposite directions. US 14 is a large needle (10.0mm) while UK 14 is a tiny needle (2.0mm). Mix these up and your project will be wildly wrong." },
      { heading: "Knitting Needle Size Reference", content: "Here are the most commonly used sizes:\n\nFor lace and fingering weight yarn: US 0\u20133 (2.0\u20133.25mm). These tiny needles create the fine gauge needed for socks, shawls, and delicate garments.\n\nFor sport and DK weight: US 3\u20137 (3.25\u20134.5mm). The sweet spot for lightweight garments, baby items, and accessories.\n\nFor worsted and aran weight: US 7\u20139 (4.5\u20135.5mm). The most popular range. This is where most beginners start.\n\nFor bulky weight: US 10\u201311 (6.0\u20138.0mm). Great for quick projects like chunky scarves and blankets.\n\nFor super bulky and jumbo: US 13\u201350 (9.0\u201325.0mm). These oversized needles are used for arm knitting and extreme chunky projects." },
      { heading: "Crochet Hook Sizing", content: "Crochet hooks use letter sizes in the US (B through S) alongside millimeter sizes. The letter system only covers hooks from 2.25mm to 15.75mm, so very small and very large hooks are referenced only by millimeter size.\n\nSteel crochet hooks (used for thread crochet and lace) have their own separate numbering system where the numbers go in the opposite direction: steel size 14 is the smallest (0.75mm) and steel size 00 is the largest (3.5mm).\n\nThe most commonly used crochet hooks are H/8 (5.0mm) for worsted weight and I/9 (5.5mm) for slightly looser worsted. These two hooks cover the majority of crochet patterns." },
      { heading: "When to Go Up or Down a Size", content: "If your gauge swatch has too many stitches per inch, your tension is tight \u2014 go up one needle size. If your swatch has too few stitches per inch, your tension is loose \u2014 go down one size.\n\nSome crafters consistently knit tight and always need to go up a size from the pattern recommendation. Others consistently knit loose. Learning your personal tendency saves time on future projects.\n\nUse our Needle and Hook Size Converter to instantly see any size across all four systems, so you can confidently work from patterns written in any country's notation." },
    ],
  },
  {
    slug: "gauge-calculator-guide",
    title: "How to Calculate and Adjust Gauge in Knitting and Crochet",
    description: "Learn why gauge matters, how to measure it accurately, and how to resize patterns when your gauge doesn't match. Step-by-step guide with examples.",
    toolSlug: "gauge-calculator",
    date: "2026-02-02",
    keywords: ["knitting gauge", "crochet gauge", "how to measure gauge", "gauge swatch", "resize knitting pattern", "stitch gauge calculator"],
    sections: [
      { heading: "What Is Gauge and Why It Matters", content: "Gauge is the number of stitches and rows in a measured section of knitting or crochet, typically measured over 4 inches (10cm). It's the single most important factor in determining whether your finished project will be the right size.\n\nConsider this: if a sweater pattern calls for 5 stitches per inch and you knit at 5.5 stitches per inch, that half-stitch difference means your 40-inch chest sweater will actually measure about 36 inches. That's a full size smaller than intended.\n\nFor blankets and scarves where exact dimensions are flexible, gauge is less critical. But for garments, hats, socks, and anything that needs to fit a specific size, gauge is non-negotiable." },
      { heading: "How to Make and Measure a Gauge Swatch", content: "Cast on enough stitches for at least 6 inches of fabric (more than the 4-inch measurement area). Work in the stitch pattern specified by the pattern for at least 6 inches in height.\n\nBind off loosely, then wash and block the swatch exactly as you plan to treat the finished project. Some yarns change gauge dramatically after washing \u2014 especially cotton, which tends to grow.\n\nLay the swatch flat on a hard surface without stretching. Place a ruler horizontally across the middle (not at the edges, which tend to curl). Count the number of stitches across 4 inches. Then turn the ruler vertically and count rows over 4 inches.\n\nFor the most accurate measurement, count to the nearest half-stitch. If you see 18 stitches over 4 inches, your gauge is 4.5 stitches per inch." },
      { heading: "Adjusting Your Gauge", content: "If you have more stitches per inch than the pattern calls for (tight knitter), go up one needle or hook size and swatch again. If you have fewer stitches per inch (loose knitter), go down one size.\n\nSometimes it takes 2\u20133 swatches to match gauge. This feels tedious, but it's much faster than ripping out and reknitting an entire sweater.\n\nSome knitters find they can match stitch gauge but not row gauge (or vice versa). Stitch gauge is almost always more important because most patterns adjust length by measurements rather than row counts." },
      { heading: "Resizing Patterns to Your Gauge", content: "If you simply cannot match gauge (some yarn and needle combinations just won't cooperate), you can resize the pattern mathematically.\n\nThe formula is: New stitch count = (original stitch count \u00F7 original gauge) \u00D7 your gauge. For example, if a pattern says to cast on 100 stitches at 5 st/inch, and your gauge is 4.5 st/inch, you'd cast on: (100 \u00F7 5) \u00D7 4.5 = 90 stitches.\n\nOur Gauge Calculator handles this automatically, including stitch multiple rounding, so every recalculated number works with your stitch pattern." },
    ],
  },
  {
    slug: "yarn-weight-chart-guide",
    title: "Yarn Weight Chart \u2014 From Lace to Jumbo with Needle Sizes and Gauge Ranges",
    description: "The complete yarn weight classification guide. Learn the difference between DK, worsted, and bulky yarn, plus recommended needle sizes and gauges for each weight.",
    toolSlug: "yarn-weight-chart",
    date: "2026-02-02",
    keywords: ["yarn weight chart", "yarn weight categories", "DK vs worsted", "yarn weight guide", "CYC yarn standards", "yarn weight comparison"],
    sections: [
      { heading: "The Yarn Weight System Explained", content: "The Craft Yarn Council (CYC) established a standardized numbering system from 0 to 7 that classifies yarns by thickness. This system is now printed on most yarn labels worldwide, making it easier to substitute yarns across brands.\n\nThe categories are: 0 (Lace), 1 (Super Fine/Fingering), 2 (Fine/Sport), 3 (Light/DK), 4 (Medium/Worsted), 5 (Bulky), 6 (Super Bulky), and 7 (Jumbo). The number refers to the weight category, not the number of plies or any measurement of the yarn itself." },
      { heading: "Weight Categories in Detail", content: "Lace (0) is the thinnest yarn, with 32+ stitches per 4 inches on US 000\u20131 needles. It's used for delicate shawls, doilies, and fine lacework. Skeins typically contain 400\u20131,000+ yards.\n\nFingering/Sock (1) knits at 27\u201332 stitches per 4 inches on US 1\u20133 needles. It's the standard for socks, lightweight shawls, and detailed colorwork like Fair Isle. This weight has seen a huge surge in popularity.\n\nSport (2) knits at 23\u201326 stitches per 4 inches on US 3\u20135. It sits between fingering and DK, great for baby items and lightweight garments.\n\nDK (3) knits at 21\u201324 stitches per 4 inches on US 5\u20137. DK stands for Double Knitting, a British term. It's versatile for garments, accessories, and blankets.\n\nWorsted (4) is the most popular weight worldwide, knitting at 16\u201320 stitches per 4 inches on US 7\u20139. Most beginner patterns and the majority of yarn available in craft stores are worsted weight.\n\nBulky (5) knits at 12\u201315 stitches per 4 inches on US 9\u201311. It works up quickly and is popular for chunky accessories, quick blankets, and winter garments.\n\nSuper Bulky (6) knits at 7\u201311 stitches per 4 inches on US 11\u201317. Extremely fast projects. Popular for arm-knitting and chunky home decor.\n\nJumbo (7) is the thickest, using US 17+ needles or even PVC pipes. Used for extreme chunky blankets and novelty projects." },
      { heading: "US, UK, and Australian Yarn Terms", content: "The same yarn weight often has different names in different countries, which causes confusion when following international patterns.\n\nUS Fingering = UK 4-ply = AU 4-ply. US Sport = UK 5-ply = AU 5-ply. US DK = UK DK = AU 8-ply. US Worsted = UK Aran = AU 10-ply. US Bulky = UK Chunky = AU 12-ply.\n\nThe biggest source of confusion is that UK 'double knitting' and US 'worsted' are not the same weight. UK DK is thinner than US worsted. Check the gauge range on the label to be sure." },
      { heading: "How to Identify Unlabeled Yarn", content: "If you have yarn without a label (from a destash, thrift store, or grandmother's attic), use the wraps-per-inch method: wrap the yarn snugly around a ruler for one inch without overlapping or stretching. Count the wraps.\n\n18+ wraps = lace or fingering. 14\u201318 = fingering to sport. 12\u201314 = sport to DK. 9\u201312 = DK to worsted. 7\u20139 = worsted to bulky. 5\u20137 = bulky to super bulky. Fewer than 5 = jumbo.\n\nOur Yarn Weight Chart tool includes an interactive WPI guide that matches your measurement to the correct weight category, along with recommended needle/hook sizes." },
    ],
  },
  {
    slug: "stitch-counter-guide",
    title: "How to Count Stitches and Rows \u2014 Tips for Accurate Tracking",
    description: "Learn techniques for counting stitches and rows in knitting and crochet. Tips for staying on track with complex patterns, plus how digital counters can help.",
    toolSlug: "stitch-counter",
    date: "2026-02-03",
    keywords: ["how to count stitches", "row counter knitting", "stitch counter app", "counting rows crochet", "keep track of knitting rows", "digital row counter"],
    sections: [
      { heading: "Why Accurate Counting Matters", content: "Losing track of your row count is the most common source of mistakes in knitting and crochet. Miss one row of shaping and your sleeves won't match. Lose count in a lace repeat and the pattern falls apart.\n\nAccurate counting is especially critical for garment shaping (increasing and decreasing at specific intervals), colorwork patterns that repeat over a set number of rows, lace patterns where every row is different, and any pattern where two pieces need to match (like sleeves or sock pairs)." },
      { heading: "Manual Counting Techniques", content: "For stockinette, each V-shape on the right side represents one stitch across. Each horizontal ridge between V-columns is one row. For garter stitch, every ridge (bump) represents two rows.\n\nIn crochet, each stitch is clearly visible as a separate post. Rows are easier to count in crochet than knitting because each row is taller.\n\nPlace a locking stitch marker every 10 or 20 rows to create reference points. This way, if you lose count, you only need to recount from the last marker, not from the beginning.\n\nFor complex patterns, photocopy the pattern and use a ruler or sticky note to track your current row. Move it down one line as you complete each row." },
      { heading: "Digital Counters vs. Physical Counters", content: "Physical row counters (the clicker type that sits on your needle) work fine for simple patterns but have limitations: they only track one number, they can get bumped accidentally, and they can't be set to alert you at specific rows.\n\nDigital counters like our Stitch Counter tool solve all of these problems. You can run multiple counters at once (row count, pattern repeats, shaping intervals), set reminders at specific rows, and your count saves automatically if you close the browser.\n\nThe key advantage of a phone-based counter is that you always have your phone with you. Dedicated physical counters get lost or forgotten." },
      { heading: "Staying on Track with Complex Patterns", content: "For patterns with multiple simultaneous instructions (like 'decrease every 6th row AND work cable pattern every 8th row'), use a separate counter for each instruction. Our tool lets you name each counter so you don't mix them up.\n\nFor colorwork charts, use a row counter in combination with the chart. Some crafters use a magnetic board with the chart and move a magnetic strip up one row at a time.\n\nIf you put your project down for days or weeks, always write a note about exactly where you stopped. Future you will thank past you. Even just 'Row 47, about to start decrease' is enough to pick up confidently." },
    ],
  },
  {
    slug: "blanket-size-guide",
    title: "Blanket Size Guide \u2014 Standard Dimensions for Baby, Throw, and Bed Blankets",
    description: "Complete blanket size chart with dimensions for every standard size from lovey to California king. Plus how to calculate yarn needed and stitch counts.",
    toolSlug: "blanket-calculator",
    date: "2026-02-03",
    keywords: ["blanket sizes", "throw blanket dimensions", "baby blanket size", "crochet blanket sizes", "how big should a throw blanket be", "blanket size chart"],
    sections: [
      { heading: "Standard Blanket Sizes", content: "Blanket sizing follows general industry standards, though there's room for personal preference. Here are the standard dimensions:\n\nLovey: 12\u00D712 inches \u2014 a small security blanket for infants, often with a stuffed animal head attached. Preemie: 18\u00D724 inches \u2014 for NICU donations and premature babies. Stroller: 30\u00D735 inches \u2014 sized for strollers and car seats.\n\nBaby/Crib: 36\u00D752 inches \u2014 fits a standard crib. This is the most popular baby blanket size for gifts. Toddler: 42\u00D760 inches \u2014 a step up from crib size, good for toddler beds.\n\nThrow: 50\u00D760 inches \u2014 the most popular blanket to make. Perfect for curling up on the sofa. Lap: 36\u00D748 inches \u2014 covers your lap while sitting, popular for wheelchair users.\n\nTwin: 66\u00D790 inches. Full/Double: 80\u00D790 inches. Queen: 90\u00D7100 inches. King: 108\u00D7100 inches. California King: 104\u00D7104 inches." },
      { heading: "Calculating Stitch Counts", content: "To calculate how many stitches to cast on or chain: multiply your desired width in inches by your stitches per inch (gauge). Then round to the nearest stitch multiple for your pattern.\n\nFor example: a 50-inch throw at 4 stitches per inch = 200 stitches. If your pattern repeats every 6 stitches plus 1, round to 199 (33 repeats of 6, plus 1) or 205 (34 repeats plus 1).\n\nFor rows: multiply your desired length by rows per inch. A 60-inch throw at 5.5 rows per inch = 330 rows.\n\nOur Blanket Calculator handles this math automatically, including stitch multiple rounding." },
      { heading: "Yarn Quantities by Blanket Size", content: "Approximate yardage for worsted weight (#4) yarn in basic stitches:\n\nBaby blanket: 900\u20131,400 yards (4\u20136 skeins of 200yd skeins). Throw: 1,500\u20132,200 yards (7\u201310 skeins). Twin: 2,500\u20133,500 yards (12\u201316 skeins). Queen: 3,500\u20134,500 yards (16\u201322 skeins). King: 4,500\u20136,000 yards (22\u201328 skeins).\n\nCable patterns increase yardage by 20\u201330%. Using bulky yarn significantly reduces yardage but increases cost per yard. Fingering weight dramatically increases yardage (and time) but creates a lighter, drapier blanket." },
      { heading: "Pillow Tuck and Overhang", content: "For bed blankets, you need to account for two additional measurements beyond the mattress size.\n\nPillow tuck is extra length at the top of the blanket that folds over the pillows. This is typically 10\u201320 inches. Without pillow tuck, a bed blanket will look too short when the bed is made.\n\nOverhang is how far the blanket drapes over the sides and foot of the mattress. A 10-inch overhang covers the mattress depth, while 15 inches provides a more luxurious drape that nearly reaches the bed frame.\n\nOur Blanket Calculator adds these automatically when you toggle pillow tuck on or set overhang inches." },
    ],
  },
  {
    slug: "increase-decrease-guide",
    title: "How to Increase and Decrease Evenly Across a Row \u2014 The Math Made Easy",
    description: "Learn how to space increases and decreases evenly in knitting and crochet. Step-by-step math formula with examples for any stitch count.",
    toolSlug: "increase-decrease-calculator",
    date: "2026-02-04",
    keywords: ["increase evenly across row", "decrease evenly knitting", "distribute increases crochet", "evenly space decreases", "knitting math", "increase calculator"],
    sections: [
      { heading: "The Problem with Evenly Spaced Changes", content: "Patterns often say 'increase 8 stitches evenly across the row' without telling you where to put them. If you cluster them together or space them unevenly, you'll get lumps, flares, or puckering in your fabric.\n\nThe goal is to distribute increases or decreases as evenly as possible across the row so the fabric changes size gradually and smoothly. This is simple division, but it gets tricky when the numbers don't divide evenly." },
      { heading: "The Basic Formula", content: "For increases: divide your current stitch count by the number of increases. The result tells you how many stitches to work between each increase.\n\nExample: you have 80 stitches and need to increase 10. 80 \u00F7 10 = 8. So you work 8 stitches, make 1 increase, and repeat across the row. You'll end with 90 stitches.\n\nFor decreases: divide your current stitch count by the number of decreases. Since each decrease uses two stitches, the spacing is slightly different.\n\nExample: you have 90 stitches and need to decrease to 80 (10 decreases). 90 \u00F7 10 = 9. So you work 7 stitches, K2tog (or SC2tog), and repeat. Each group of 9 stitches becomes 8." },
      { heading: "Handling Remainders", content: "When the math doesn't divide evenly, you need to distribute the remainder. Say you have 100 stitches and need to increase 7. 100 \u00F7 7 = 14 remainder 2.\n\nThe solution: most sections will have 14 stitches between increases, but 2 sections will have 15. Distribute the longer sections evenly (not all at the end). For example: work 15, inc, work 14, inc, work 14, inc, work 15, inc, work 14, inc, work 14, inc, work 14, inc.\n\nOur Increase/Decrease Calculator handles all of this automatically, including remainder distribution, and generates written instructions for both knitting and crochet." },
      { heading: "Increase and Decrease Methods", content: "For knitting increases: M1L (Make 1 Left) and M1R (Make 1 Right) are nearly invisible. KFB (Knit Front and Back) is easier but leaves a small bump.\n\nFor knitting decreases: K2tog leans right, SSK leans left. For a centered double decrease, use S2KP (slip 2, knit 1, pass slipped stitches over).\n\nFor crochet increases: simply work 2 stitches into the same stitch. For crochet decreases: SC2tog (insert hook in next stitch, yarn over, pull through, insert hook in following stitch, yarn over, pull through, yarn over, pull through all 3 loops).\n\nThe lean direction matters for garment shaping. Use left-leaning decreases on the right side and right-leaning decreases on the left side for a polished, symmetrical look." },
    ],
  },
  {
    slug: "stripe-pattern-guide",
    title: "How to Plan Stripe Patterns \u2014 Random, Weighted, and Sequence Stripes",
    description: "Design beautiful stripe patterns for knitting and crochet. Learn about random stripes, weighted color distribution, and how to use scrap yarn effectively.",
    toolSlug: "stripe-generator",
    date: "2026-02-04",
    keywords: ["stripe pattern generator", "random stripe pattern", "scrap yarn stripe", "knitting stripe pattern", "crochet stripe ideas", "color stripe calculator"],
    sections: [
      { heading: "Why Plan Your Stripes?", content: "Unplanned stripes often end up with awkward color combinations, too much of one color, or a pattern that looks random in a bad way. Planning your stripes in advance lets you control the visual balance, ensure you have enough of each color, and catch any combinations that don't work before you commit to them.\n\nThe three main approaches are sequence stripes (A-B-C-A-B-C), fixed-width random, and weighted random. Each creates a different visual effect." },
      { heading: "Sequence Stripes", content: "Sequence stripes follow a repeating order: color A, then B, then C, then back to A. This creates a predictable, regular pattern. It works best with 2\u20134 colors where you want a clean, graphic look.\n\nThe stripe width can be uniform (every stripe is 4 rows) or varied within the sequence (A gets 6 rows, B gets 4, C gets 2). Varied widths within a sequence create visual rhythm while still feeling orderly.\n\nA classic two-color stripe in equal widths is timeless and works for everything from baby blankets to adult sweaters." },
      { heading: "Random and Weighted Stripes", content: "Random stripes look organic and modern. True random selection can produce unwanted effects (like the same color appearing three times in a row), so our generator prevents consecutive same-color stripes.\n\nWeighted random is the secret weapon for scrap yarn projects. Assign more weight to colors you have a lot of and less to colors you have only a little. The generator will use your abundant colors more frequently while still mixing in the accent colors.\n\nThis is the fastest way to use up a stash while still creating a cohesive blanket or scarf. The visual result looks intentional even though the order is random." },
      { heading: "Practical Tips for Stripe Knitting and Crochet", content: "Carrying yarn up the side: for stripes of 2\u20134 rows, you can carry the unused color up the side edge without cutting. Twist it around the working yarn every 2 rows to prevent long floats.\n\nFor wider stripes (6+ rows), it's cleaner to cut the yarn and rejoin. In crochet, you can change colors in the last pull-through of the row before.\n\nEven-row stripes (2, 4, 6 rows) are easier in flat knitting because you always change colors on the same side. Odd-row stripes mean you alternate which side the color change happens on.\n\nOur Stripe Generator creates a visual preview with exact row counts and per-color yardage percentages, so you can plan before you start." },
    ],
  },
  {
    slug: "knitting-abbreviations-guide",
    title: "Knitting and Crochet Abbreviations \u2014 The Complete Reference Guide",
    description: "Every knitting and crochet abbreviation explained. Includes US vs UK term differences, a searchable glossary, and a pattern translator tool.",
    toolSlug: "abbreviation-glossary",
    date: "2026-02-05",
    keywords: ["knitting abbreviations", "crochet abbreviations", "US vs UK crochet terms", "what does SSK mean", "knitting terms glossary", "crochet stitch abbreviations"],
    sections: [
      { heading: "Why Abbreviations Matter", content: "Knitting and crochet patterns are written almost entirely in abbreviations. A line like 'K2, P2, C4F, K2, P2' looks like code to a beginner, but it's actually a precise set of instructions: knit 2, purl 2, cable 4 front, knit 2, purl 2.\n\nLearning abbreviations is the gateway to following any pattern. Once you know them, you can work from patterns published anywhere in the world (with the important caveat of US vs UK differences, which we'll cover below)." },
      { heading: "Essential Knitting Abbreviations", content: "The basics: K = knit, P = purl, CO = cast on, BO = bind off, st(s) = stitch(es), rep = repeat, RS = right side, WS = wrong side.\n\nIncreases: M1 = make one, M1L = make one left, M1R = make one right, KFB = knit front and back, YO = yarn over.\n\nDecreases: K2tog = knit two together (right-leaning), SSK = slip slip knit (left-leaning), P2tog = purl two together, S2KP = slip 2, knit 1, pass slipped stitches over (centered).\n\nCables: C4F = cable 4 front, C4B = cable 4 back. The number tells you how many stitches are involved, and F/B tells you which direction the cable crosses.\n\nColorwork: MC = main color, CC = contrast color, CC1/CC2 = first/second contrast colors." },
      { heading: "The US vs UK Problem", content: "This is the single biggest source of confusion in crochet. US and UK terms use the same words for different stitches, offset by one.\n\nUS Single Crochet (SC) = UK Double Crochet (DC). US Half Double Crochet (HDC) = UK Half Treble (HTR). US Double Crochet (DC) = UK Treble (TR). US Treble (TR) = UK Double Treble (DTR).\n\nIf you follow a UK pattern using US definitions, every stitch will be one size too short, and your project will come out dramatically smaller and denser than intended.\n\nAlways check whether a pattern uses US or UK terms. Look for clues: if it mentions 'treble' for what seems like a basic stitch, it's probably UK. Our Abbreviation Glossary has a US/UK toggle that shows equivalents for every term." },
      { heading: "Using Our Pattern Translator", content: "Our Abbreviation Glossary includes a Pattern Translator mode. Paste any line from a pattern, and every abbreviation gets highlighted in color with a tooltip showing the full name and description.\n\nThis is especially useful for beginners working through their first pattern, crafters switching between knitting and crochet, and anyone working from an international pattern where the terms aren't familiar.\n\nThe glossary covers 70+ abbreviations across knitting and crochet, with filtering by craft type and category (basic, increase, decrease, texture, colorwork, finishing)." },
    ],
  },
  {
    slug: "spinning-wheel-guide",
    title: "Spinning Wheel Ratios Explained \u2014 How to Calculate Drive Ratio and TPI",
    description: "Learn how spinning wheel ratios work, how to calculate TPI, and how to choose the right whorl for the yarn weight you want to spin.",
    toolSlug: "spinning-ratio-calculator",
    date: "2026-02-05",
    keywords: ["spinning wheel ratio", "drive ratio calculator", "TPI spinning", "how to calculate spinning ratio", "whorl size spinning", "spinning wheel setup"],
    sections: [
      { heading: "What Is Drive Ratio?", content: "The drive ratio is the number of times the flyer (or bobbin) rotates for each turn of the drive wheel. A ratio of 8:1 means the flyer spins 8 times for every complete turn of the big wheel.\n\nHigher ratios add more twist per treadle, which is what you want for thin, strong yarn (like sock or lace weight). Lower ratios add less twist per treadle, ideal for thick, soft yarn (like bulky weight).\n\nTo calculate your ratio: measure the diameter of your drive wheel and divide by the diameter of the whorl (the pulley on the flyer). If your wheel is 22 inches and the whorl is 2.5 inches: 22 \u00F7 2.5 = 8.8:1." },
      { heading: "Understanding TPI (Twists Per Inch)", content: "TPI (twists per inch) is the direct measure of how tightly your yarn is spun. More twists = stronger, harder yarn. Fewer twists = softer, loftier yarn.\n\nGeneral TPI guidelines: lace weight = 12\u201320+ TPI, fingering/sock = 8\u201314 TPI, sport/DK = 5\u20138 TPI, worsted = 3\u20136 TPI, bulky = 2\u20134 TPI.\n\nTPI depends on both your wheel ratio and how fast you draft (pull the fiber out). A high ratio with slow drafting produces very high TPI (tightly spun). A high ratio with fast drafting produces moderate TPI. Our TPI Calculator factors in both ratio and draft speed." },
      { heading: "Choosing the Right Whorl", content: "Most spinning wheels come with 2\u20133 whorls of different sizes. Smaller whorls create higher ratios (more twist). Larger whorls create lower ratios (less twist).\n\nFor lace and fingering: use your smallest whorl (highest ratio, typically 10:1 to 15:1). For DK and worsted: use a medium whorl (6:1 to 10:1). For bulky: use your largest whorl (4:1 to 6:1).\n\nIf your wheel's ratio range doesn't cover the yarn weight you want, you may need an aftermarket whorl set. Many wheel manufacturers sell additional whorls." },
      { heading: "Plying for Balanced Yarn", content: "Plying is twisting two or more singles together in the opposite direction of spinning. The plying twist counteracts the spinning twist, creating balanced yarn that hangs straight without curling.\n\nThe rule of thumb for balanced 2-ply yarn: ply at roughly 60% of your singles TPI in the opposite direction. If you spin your singles at 10 TPI in a clockwise (Z-twist) direction, ply at about 6 TPI counterclockwise (S-twist).\n\nFor 3-ply yarn, use about 50% of the singles TPI. The additional plies provide more structural stability, so less plying twist is needed.\n\nOur Plying Calculator handles the math and reminds you about ply direction." },
    ],
  },
  {
    slug: "cross-stitch-fabric-guide",
    title: "Cross Stitch Fabric Calculator \u2014 How to Figure Out the Right Size Aida Cloth",
    description: "Calculate the finished size of any cross stitch pattern on different fabric counts. Learn how much fabric and floss you need, including margins for framing.",
    toolSlug: "cross-stitch-calculator",
    date: "2026-02-06",
    keywords: ["cross stitch fabric calculator", "aida cloth sizes", "cross stitch finished size", "how much aida fabric", "cross stitch thread calculator", "cross stitch framing margins"],
    sections: [
      { heading: "How Fabric Count Works", content: "Cross stitch fabric is measured by count \u2014 the number of squares (or thread intersections) per inch. Aida 14 has 14 squares per inch, so a pattern that's 140 stitches wide will be exactly 10 inches wide on Aida 14.\n\nThe higher the count, the smaller each stitch, and the smaller the finished piece. The same 140\u00D7140 stitch pattern would be 10\u00D710 inches on Aida 14, but only 7.8\u00D77.8 inches on Aida 18, and 12.7\u00D712.7 inches on Aida 11.\n\nChoosing your fabric count is a trade-off between detail (higher counts show finer detail), speed (lower counts are faster because each stitch is bigger), and finished size." },
      { heading: "Evenweave and Linen", content: "Aida is the most common cross stitch fabric, but evenweave and linen are popular for advanced stitchers. These fabrics don't have the obvious grid that Aida has \u2014 instead, you count individual threads.\n\nThe key difference is stitching over two. On evenweave and linen, each cross stitch typically covers 2 threads in each direction. This means 28-count evenweave stitched over two produces the same size as 14-count Aida.\n\nWhy bother? Evenweave and linen drape better, look more refined, and allow for fractional stitches and specialty stitches that don't work well on Aida's rigid grid." },
      { heading: "How Much Fabric to Buy", content: "Take your finished design dimensions and add margin on all four sides. The standard margin is 3 inches per side for framing in a standard frame. For scroll frames or Q-snaps, you may need more.\n\nSo a design that finishes at 10\u00D714 inches needs at least 16\u00D720 inches of fabric (10+3+3 by 14+3+3).\n\nAlways round up to the next available fabric cut size. Aida is commonly sold in 12\u00D718, 15\u00D718, and 18\u00D725 inch precuts, or by the yard from a bolt.\n\nOur Cross Stitch Calculator adds your chosen margin automatically and shows the total fabric dimensions needed." },
      { heading: "How Much Floss Do You Need?", content: "A single full cross stitch uses approximately 1.1 inches of 6-strand embroidery floss (when stitching with the standard 2 strands). A DMC skein contains 8 meters (about 472 inches) of floss.\n\nSo one skein covers roughly 430 full cross stitches when using 2 strands. If your pattern has 500 stitches of DMC 310 (black), you need 2 skeins.\n\nUsing more strands (3 or 4, common on lower-count fabric for better coverage) increases the floss needed proportionally. Half stitches and backstitching use less floss per stitch than full crosses.\n\nOur thread estimator calculates this per color based on your stitch count and strand count." },
    ],
  },
  {
    slug: "weaving-sett-guide",
    title: "How to Calculate Sett for Weaving \u2014 EPI Guide for Every Yarn Weight",
    description: "Learn how to determine the right sett (ends per inch) for your yarn and weave structure. Includes warp length calculation and reed substitution charts.",
    toolSlug: "weaving-sett-calculator",
    date: "2026-02-06",
    keywords: ["weaving sett calculator", "ends per inch", "EPI weaving", "how to calculate sett", "weaving warp length", "reed substitution"],
    sections: [
      { heading: "What Is Sett and Why It Matters", content: "Sett (also called EPI \u2014 Ends Per Inch) is the number of warp threads per inch of weaving. Getting the sett right is fundamental to the quality of your woven fabric.\n\nToo few ends per inch (open sett) and your fabric will be sleazy \u2014 loose, unstable, and prone to shifting. Too many ends per inch (close sett) and your fabric will be stiff, warp-dominant, and difficult to beat evenly.\n\nThe right sett depends on two things: the thickness of your yarn and the weave structure you're using." },
      { heading: "The WPI Method", content: "The standard way to determine sett is the WPI (Wraps Per Inch) method. Wrap your yarn around a ruler for one inch, laying each wrap snugly next to the last without overlapping or compressing.\n\nCount the wraps. This is your maximum possible sett \u2014 the theoretical maximum number of ends you could pack into one inch. Your actual weaving sett will be a percentage of this, determined by your weave structure.\n\nFor plain weave: use 50\u201360% of your WPI. For twill: use 60\u201370%. For satin: use 70\u201380%. For lace weaves: use 30\u201340%.\n\nFor example, if your yarn wraps at 12 WPI: plain weave sett = 6\u20137 EPI, twill sett = 7\u20138 EPI." },
      { heading: "Calculating Warp Length", content: "Your total warp length must account for more than just the finished project length. You need to add loom waste (typically 18\u201336 inches of warp that can't be woven because it's tied to the loom), sampling length (6\u201312 inches to test sett and structure before weaving the real project), take-up (the warp gets shorter as it goes over and under weft threads, typically 5\u201310%), and shrinkage (yarn shrinks when washed, varying by fiber).\n\nShrinkage by fiber: cotton shrinks about 10%, wool 10\u201315%, linen 3\u20135%, silk 5\u20138%, synthetics 2\u20133%.\n\nOur Warp Length Calculator adds all of these factors and shows total yardage for both warp and weft." },
      { heading: "Reed Substitution", content: "Your reed's dent (spaces per inch) doesn't always match your desired sett. For example, you may want a sett of 15 EPI but only have a 12-dent reed.\n\nThe solution is threading multiple ends per dent in some or all dents. For 15 EPI in a 12-dent reed: 15 \u00F7 12 = 1.25 ends per dent. Thread 1 end in some dents and 2 in others, alternating to distribute evenly.\n\nThe pattern would be: 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2 \u2014 that's 15 ends in 12 dents. Our Reed Substitution calculator figures this out for any sett and reed combination." },
    ],
  },
  {
    slug: "project-cost-guide",
    title: "How Much Does It Cost to Crochet a Blanket? The Honest Price Breakdown",
    description: "Calculate the real cost of knitting and crochet projects including yarn, notions, and your time. Is it cheaper to make or buy? We break down the numbers.",
    toolSlug: "project-cost-calculator",
    date: "2026-02-07",
    keywords: ["cost to crochet blanket", "knitting project cost", "is it cheaper to knit or buy", "handmade pricing", "yarn cost calculator", "craft project budget"],
    sections: [
      { heading: "Material Costs: Yarn", content: "Yarn is the biggest expense in any project. The cost varies enormously depending on fiber content, brand, and where you shop.\n\nBudget acrylic (like Red Heart Super Saver) runs $4\u20137 per skein, with each skein containing about 360 yards of worsted weight. A throw blanket needs about 8 skeins, putting material cost at $32\u201356.\n\nMid-range yarn (like Caron Simply Soft or Paintbox) runs $5\u201310 per skein. Premium yarn (Malabrigo, Cascade) runs $10\u201320 per skein. Luxury fibers (cashmere, qiviut) can be $30\u201380+ per skein.\n\nThe same throw blanket in premium wool might cost $120\u2013200 in materials alone." },
      { heading: "Hidden Costs: Notions and Extras", content: "Beyond yarn, projects often need notions: buttons ($3\u201310), zippers ($5\u201315), stitch markers ($5\u201312 for a set), tapestry needles ($3\u20136), project bags ($10\u201330), and pattern costs ($0\u201312 for individual patterns, $50\u2013100+ for books).\n\nIf you're a new crafter, add one-time startup costs: needles or hooks ($8\u201350 depending on sets vs. singles), blocking mats ($20\u201340), scissors, measuring tape. These costs amortize across projects but are real for your first project.\n\nOur Project Cost Calculator lets you add all notions and extras to get a true total cost." },
      { heading: "The Time Factor", content: "Handmade items take significant time. A throw blanket in worsted weight takes roughly 40\u201370 hours. A sweater takes 50\u2013100+ hours. Even a simple hat takes 5\u201310 hours.\n\nIf you value your time at minimum wage ($15/hour in many states), that throw blanket represents $600\u20131,050 of labor. Even at a modest $5/hour, it's $200\u2013350 of time.\n\nThis is why handmade items sold at fair prices seem expensive to non-crafters. A $200 handmade blanket, when you factor in $50 of materials and 50 hours of labor, works out to $3/hour for the maker.\n\nOur calculator shows your effective hourly rate at any selling price, helping you price fairly if you sell, or simply appreciate the true value of your handmade gifts." },
      { heading: "So Is It Cheaper to Make or Buy?", content: "For most items, buying mass-produced is cheaper in pure material + time terms. A comparable quality store-bought throw costs $30\u201380. Your handmade version costs $40\u201360 in materials plus 50 hours of time.\n\nBut this comparison misses the point. Handmade items are custom-sized, custom-colored, made from the exact fiber you chose, and carry emotional value that mass-produced items can't match.\n\nWhere handmade shines economically: luxury items (a cashmere scarf costs $200+ retail but $50\u201380 to make), custom sizes (baby blankets in specific dimensions), and gifts (the time invested IS the gift).\n\nWhere buying is clearly cheaper: basic socks, simple scarves, and anything you can find at discount retailers. The math only works for handmade when the item is premium quality or has emotional significance." },
    ],
  },
  {
    slug: "color-pooling-guide",
    title: "Color Pooling Calculator \u2014 How to Plan Pooling with Variegated Yarn",
    description: "Learn the math behind planned pooling in crochet and knitting. Calculate the exact chain count to make variegated yarn pool into argyle patterns.",
    toolSlug: "color-pooling-calculator",
    date: "2026-02-07",
    keywords: ["color pooling crochet", "planned pooling tutorial", "variegated yarn pooling", "color pooling stitch count", "planned pooling moss stitch", "argyle from variegated yarn"],
    sections: [
      { heading: "What Is Color Pooling?", content: "Color pooling (also called planned pooling) is a technique that exploits the repeating color sequence in variegated yarn to create geometric patterns \u2014 typically argyle diamonds or plaid-like grids \u2014 from a single ball of multicolored yarn.\n\nThe secret is matching your stitch count to the yarn's color repeat length. When the number of stitches per row equals the number of stitches in one complete color cycle, each color stacks directly above itself, forming vertical columns instead of diagonal stripes.\n\nThe result looks like you used multiple colors and an advanced technique, but it's actually a single yarn and a basic stitch." },
      { heading: "How to Measure Your Yarn's Color Repeat", content: "Work a swatch of at least 20 stitches in the stitch you plan to use (usually moss stitch or single crochet). As you work, count exactly how many stitches each color section lasts before changing to the next color.\n\nWrite down every section: Color A = 4 stitches, Color B = 3 stitches, Color C = 4 stitches, Color D = 3 stitches. The total (in this example, 14) is your color repeat length.\n\nAccuracy is critical. Even being off by one stitch will cause the colors to shift and the pattern won't pool. Measure across several repeats to make sure the color sections are consistent.\n\nSome yarns have very consistent repeats (great for pooling). Others vary slightly from repeat to repeat (harder to pool). Yarns specifically marketed for pooling tend to be very consistent." },
      { heading: "The Magic Number: Your Foundation Chain", content: "Your foundation chain should equal the total stitch count of one complete color repeat. Using the example above: chain 14 (plus any chains needed for turning, depending on your stitch).\n\nIf pooling doesn't align perfectly, try adding or subtracting 1\u20132 chains. Sometimes the turning chain or edge stitches shift the alignment slightly. Small adjustments can make the difference between a jumbled mess and perfect columns.\n\nThis is why our Color Pooling Calculator includes adjust buttons (\u00B11 and \u00B12). Enter your color sections, and the preview instantly shows whether the colors align. Adjust until you see vertical columns." },
      { heading: "Best Stitches for Pooling", content: "Moss stitch (also called linen stitch or granite stitch) is the most popular for pooling because each stitch sits directly above the stitch two rows below, creating clean stacking. The technique: SC in next stitch, CH 1, skip 1, repeat.\n\nSingle crochet also works well but can create a denser fabric. It's simpler than moss stitch, making it a good starting point for pooling beginners.\n\nGarter stitch works for knitting pooling. The texture of garter stitch helps hide any slight misalignments.\n\nHook or needle size affects pooling. A larger hook means each stitch uses more yarn, potentially pushing colors out of alignment. If pooling worked in your swatch but not your project, try matching your swatch's exact tension." },
    ],
  },
  {
    slug: "thread-conversion-guide",
    title: "DMC to Anchor Thread Conversion Chart \u2014 The Complete Searchable Guide",
    description: "Convert between DMC, Anchor, and Cosmo embroidery thread numbers instantly. Includes a searchable database, palette builder, and bulk conversion tool.",
    toolSlug: "thread-converter",
    date: "2026-02-08",
    keywords: ["DMC to Anchor conversion", "embroidery thread conversion", "DMC thread chart", "Anchor to DMC", "Cosmo thread equivalent", "embroidery floss brands"],
    sections: [
      { heading: "Why You Need Thread Conversions", content: "Embroidery patterns specify colors by brand number \u2014 usually DMC, the most popular brand worldwide. But you might prefer Anchor (popular in Europe), Cosmo (a Japanese brand), or another brand. Maybe your local shop doesn't carry DMC, or a specific DMC color is out of stock.\n\nThread conversion charts map equivalent colors across brands so you can substitute without guessing. The key word is equivalent, not identical \u2014 different brands use different dye processes, so colors are close matches rather than perfect duplicates." },
      { heading: "DMC, Anchor, and Cosmo Compared", content: "DMC is the global standard with 500 numbered colors. Their numbering system has no logical order \u2014 DMC 310 is black, DMC 321 is red, and DMC 3865 is white. You simply have to look them up.\n\nAnchor has about 450 colors with a similarly arbitrary numbering system. Their colors tend to be very slightly different in saturation from DMC equivalents.\n\nCosmo is a Japanese brand with excellent color saturation and a silkier feel. They're gaining popularity worldwide. Their color range includes some shades that have no close DMC equivalent.\n\nFor most patterns, conversions between brands are close enough that the finished piece looks identical. For very color-critical work (like realistic portraits), compare threads in person." },
      { heading: "How to Use Our Converter", content: "Our Thread Converter offers three modes:\n\nSearch mode lets you type any thread number or color name and instantly see equivalents across all three brands. Search works with DMC numbers, Anchor numbers, Cosmo numbers, and color names like 'red' or 'forest green.'\n\nPalette mode lets you build a shopping list. Click the + button next to any search result to add it to your palette. The palette shows all selected colors with every brand's number, ready to copy or print.\n\nBulk mode handles entire pattern shopping lists. Paste a comma-separated list of DMC numbers and get all conversions at once in a printable table. This is the fastest way to convert a pattern from one brand to another." },
      { heading: "Tips for Color Matching", content: "When converting thread colors, keep these tips in mind:\n\nAlways compare threads in natural daylight, not under fluorescent or LED lights. Different lighting can dramatically change how colors appear.\n\nFor large areas of a single color, buy one skein and stitch a small sample before buying the rest. What looks right on a color card might look different when stitched.\n\nIf a conversion is marked as an approximate match, consider buying two adjacent shades and testing both. The 'wrong' shade on a chart might actually be the better visual match for your specific project.\n\nOur converter currently includes 80 of the most popular colors, with more being added regularly. If you can't find a specific number, check back soon or contact us with the colors you need most." },
    ],
  },
];

export function getBlogPost(slug: string): BlogPost | undefined {
  return blogPosts.find((p) => p.slug === slug);
}
