export interface FAQ {
  q: string;
  a: string;
}

export const toolFaqs: Record<string, FAQ[]> = {
  "yarn-calculator": [
    { q: "How do I calculate how much yarn I need?", a: "Enter your project type, size, yarn weight, and stitch pattern into our calculator. It uses industry-standard yardage estimates adjusted for your specific combination to give you an accurate total with a 10% safety buffer." },
    { q: "How much yarn do I need for a blanket?", a: "A throw blanket (50\u00D760\") typically needs 1,200\u20132,000 yards of worsted weight yarn. The exact amount depends on your stitch pattern, gauge, and yarn weight. Use our calculator for a precise estimate." },
    { q: "How many skeins of yarn do I need for a sweater?", a: "An adult sweater typically needs 1,000\u20131,800 yards depending on size and yarn weight. That\u2019s roughly 5\u20138 skeins of worsted weight yarn. Enter your specific measurements for an exact count." },
    { q: "Does stitch pattern affect yarn usage?", a: "Yes, significantly. Cable patterns use 20\u201330% more yarn than stockinette. Lace patterns use less. Brioche uses about 50% more. Our calculator adjusts for 17 different stitch patterns." },
    { q: "Should I buy extra yarn?", a: "Always. Our calculator includes a 10% buffer, but we recommend buying one extra skein from the same dye lot. Yarn from different dye lots can have subtle color differences." },
    { q: "What is yarn weight?", a: "Yarn weight refers to the thickness of the yarn strand, rated 0 (lace) through 7 (jumbo). Worsted weight (4) is the most common. Thicker yarn covers more area per yard but creates a bulkier fabric." },
  ],
  "needle-converter": [
    { q: "What size knitting needles should I use?", a: "Check your yarn label for the recommended needle size. Our converter shows the equivalent size across US, metric (mm), UK, and Japanese systems so you can match any pattern regardless of origin." },
    { q: "How do I convert US needle sizes to mm?", a: "US sizes don\u2019t follow a linear scale. For example, US 6 = 4.0mm, US 7 = 4.5mm, US 8 = 5.0mm. Our converter handles all 23 sizes from US 0 (2.0mm) to US 50 (25.0mm)." },
    { q: "What size crochet hook do I need?", a: "It depends on your yarn weight. Lace yarn uses 1.5\u20132.25mm hooks, worsted uses 5.0\u20136.0mm hooks, and bulky uses 6.5\u20139.0mm hooks. Our chart shows recommendations for every weight." },
    { q: "Are UK and US needle sizes the same?", a: "No. UK sizes run backwards \u2014 a UK 14 is 2.0mm (tiny) while a US 14 is 10.0mm (large). Our converter prevents this common confusion by showing all systems side by side." },
    { q: "What\u2019s the difference between US and metric crochet hooks?", a: "US crochet hooks use letter sizes (B through S) while metric uses millimeters. For example, US H/8 = 5.0mm. Our converter maps all 24 common hook sizes across both systems." },
    { q: "Can I substitute a different needle size?", a: "Yes, but it will change your gauge. Going up a size creates a looser, drapier fabric. Going down creates a tighter, firmer fabric. Always swatch first when substituting." },
    { q: "What size knitting needle do I need for worsted weight?", a: "Worsted weight yarn (CYC category 4) typically uses US 7\u20139 needles (4.5\u20135.5mm). The exact size depends on the pattern and your personal tension. Check your pattern for the recommended size, then swatch to confirm your gauge matches." },
    { q: "How do I convert US needle sizes to metric?", a: "US needle sizes don\u2019t follow a linear scale. Common conversions: US 4 = 3.5mm, US 6 = 4.0mm, US 7 = 4.5mm, US 8 = 5.0mm, US 10 = 6.0mm, US 15 = 10.0mm. Use our converter for the complete chart of all 23 sizes." },
    { q: "What needle size is best for beginners?", a: "US 8 (5.0mm) needles with worsted weight yarn are the most beginner-friendly combination. The stitches are large enough to see clearly and count easily, and worsted is the most widely available yarn weight with the most pattern options." },
  ],
  "gauge-calculator": [
    { q: "What is gauge in knitting and crochet?", a: "Gauge is the number of stitches and rows per unit of measurement (usually 4 inches or 10cm). It determines the finished size of your project. Even a half-stitch difference per inch can change a sweater by a full size." },
    { q: "How do I measure my gauge?", a: "Knit or crochet a swatch at least 6 inches square. Lay it flat without stretching. Measure the number of stitches across 4 inches and rows down 4 inches in the center of the swatch." },
    { q: "Why doesn\u2019t my gauge match the pattern?", a: "Everyone knits and crochets at different tensions. Try going up a needle/hook size if you have too many stitches per inch (tight), or down a size if too few (loose)." },
    { q: "Do I really need to make a gauge swatch?", a: "For anything where size matters (garments, hats, socks), absolutely yes. For blankets and scarves where exact dimensions are flexible, you can skip it but may use more or less yarn than expected." },
    { q: "How do I resize a pattern to my gauge?", a: "Use our Resize Pattern tab. Enter the pattern\u2019s gauge and your gauge, and we\u2019ll recalculate every stitch and row count, including stitch multiple rounding." },
    { q: "What is a stitch multiple?", a: "Many stitch patterns repeat over a fixed number of stitches (e.g., a cable that repeats every 8 stitches). Your total stitch count must be divisible by this number, plus any edge stitches. Our calculator handles this rounding." },
  ],
  "yarn-weight-chart": [
    { q: "What are the yarn weight categories?", a: "The Craft Yarn Council defines 8 categories: 0 (Lace), 1 (Fingering/Sock), 2 (Sport), 3 (DK), 4 (Worsted/Aran), 5 (Bulky), 6 (Super Bulky), and 7 (Jumbo). Each has specific gauge and needle size ranges." },
    { q: "What is DK weight yarn?", a: "DK (Double Knitting) is weight category 3. It\u2019s lighter than worsted, typically knits at 5.5\u20136 stitches per inch on US 5\u20137 needles. In the UK it\u2019s called DK, in Australia it\u2019s 8-ply." },
    { q: "Can I substitute DK for worsted weight?", a: "They\u2019re close but not identical. DK is thinner and will give a drapier, lighter fabric. You\u2019ll need more yardage and should adjust your needle size. Our substitution checker shows compatibility scores." },
    { q: "What does ply mean in yarn?", a: "Ply originally meant the number of strands twisted together, but it\u2019s evolved into a weight system in Australia and the UK. An 8-ply yarn is roughly DK weight, 10-ply is worsted, regardless of actual strand count." },
    { q: "What\u2019s the difference between UK and US yarn terms?", a: "US \u2018worsted\u2019 is UK \u2018aran.\u2019 US \u2018fingering\u2019 is UK \u20184-ply.\u2019 US \u2018DK\u2019 is the same in both. Our chart shows US, UK, and Australian terms side by side to prevent confusion." },
    { q: "How do I find the weight of unlabeled yarn?", a: "Wrap the yarn around a ruler for one inch without stretching. Count the wraps: 14\u201318 wraps = fingering, 10\u201312 = DK, 8\u201310 = worsted, 5\u20138 = bulky." },
    { q: "Can I substitute any yarn for another?", a: "Not freely. Yarns within the same weight category are the best substitution candidates, but fiber content, ply structure, and spin direction all affect the finished fabric. A superwash merino worsted and a cotton worsted knit at similar gauge but produce very different drape and stitch definition. Always swatch the substitute." },
    { q: "What happens if I use a different fiber?", a: "Fiber content changes drape, elasticity, warmth, and care requirements. Wool is elastic and warm but can felt. Cotton is inelastic and cool but heavy. Acrylic is machine-washable but lacks the stitch definition of natural fibers. Substituting fibers within the same weight category is possible but changes the fabric character." },
    { q: "How do I adjust my pattern for a yarn substitution?", a: "First, match the yarn weight category. Then swatch with the substitute yarn at the pattern\u2019s recommended needle size. If your gauge matches, proceed. If not, adjust your needle size up or down until gauge matches. Recalculate yardage since different fibers have different yards-per-gram ratios." },
  ],
  "stitch-counter": [
    { q: "How do I count stitches while knitting?", a: "Use our digital stitch counter. Tap the + button after each row or repeat. The large display is designed for one-handed use while your other hand holds your work." },
    { q: "Can I track multiple counters at once?", a: "Yes, you can run up to 6 independent counters simultaneously. Name each one (e.g., \u2018rows,\u2019 \u2018pattern repeats,\u2019 \u2018decreases\u2019) and track them all on one screen." },
    { q: "Will my count save if I close the browser?", a: "Yes. Your counters automatically save to your browser\u2019s local storage. They\u2019ll be right where you left them when you come back, even after closing the tab." },
    { q: "What are row reminders?", a: "Set a reminder at any row number with a note (e.g., \u2018Row 12: start decreases\u2019). When your counter reaches that row, a popup will alert you so you don\u2019t miss shaping instructions." },
    { q: "Is there an undo button?", a: "Yes. Every tap is tracked with a 50-action undo/redo history. If you accidentally tap +, just hit undo to go back." },
    { q: "Can I use this on my phone?", a: "Absolutely. The counter is designed for mobile with extra-large tap targets, one-thumb operation, and a fullscreen mode that hides browser chrome for distraction-free counting." },
  ],
  "blanket-calculator": [
    { q: "How big should a throw blanket be?", a: "A standard throw blanket is 50\u00D760 inches (127\u00D7152cm). It\u2019s the most popular size for sofa blankets. Our calculator includes 12 standard sizes from lovey (12\u00D712\") to California king (104\u00D7104\")." },
    { q: "How many chains do I need for a throw blanket?", a: "It depends on your yarn weight and gauge. With worsted yarn at 4 stitches per inch, a 50-inch throw needs about 200 chains. Enter your exact gauge into our calculator for a precise number with stitch multiple rounding." },
    { q: "How much yarn do I need for a baby blanket?", a: "A baby/crib blanket (36\u00D752\") typically needs 900\u20131,400 yards of worsted weight yarn, or about 4\u20136 skeins. The exact amount depends on your stitch pattern and gauge." },
    { q: "What is pillow tuck?", a: "Pillow tuck adds extra length (about 20 inches) to the top of a bed blanket so it can fold over the pillows for a finished look. Toggle it on in our calculator for bed-sized blankets." },
    { q: "How do I calculate overhang for a bed blanket?", a: "Overhang is how far the blanket drapes over the sides of the mattress. Typical overhang is 10\u201315 inches. Our calculator adds this to both sides and the foot of the bed automatically." },
    { q: "How many skeins do I need?", a: "Enter your skein yardage (found on the label) and our calculator divides total yardage by skein yardage, rounding up. We include a 10% buffer for swatching and joining." },
  ],
  "increase-decrease-calculator": [
    { q: "How do I increase evenly across a row?", a: "Divide your current stitch count by the number of increases. Our calculator gives you exact stitch-by-stitch instructions like \u2018K7, M1, repeat 11 times\u2019 with balanced distribution of any remainders." },
    { q: "What\u2019s the difference between increasing in a row vs. in the round?", a: "In a flat row, you have edges, so increases are distributed between the first and last stitch. In the round, increases are distributed evenly around the full circumference with no edges to account for." },
    { q: "How do I decrease evenly?", a: "Same principle as increasing. Enter your current count and target count, and we\u2019ll generate instructions using K2tog (knitting) or SC2tog (crochet) spaced evenly across the row." },
    { q: "What does M1 mean?", a: "M1 (Make 1) is a nearly invisible increase. You lift the bar between two stitches and knit into the back of it. M1L leans left, M1R leans right. It\u2019s the cleanest increase method." },
    { q: "What if the number doesn\u2019t divide evenly?", a: "Our calculator handles remainders by distributing them across the row. Some sections will have one extra stitch between increases. The written instructions show exactly where." },
    { q: "Can I get crochet instructions too?", a: "Yes. We generate both knitting and crochet instructions side by side. Knitting uses M1/K2tog terminology, crochet uses \u20182 SC in next st\u2019 and \u2018SC2tog.\u2019" },
  ],
  "stripe-generator": [
    { q: "How do I plan stripes for a blanket?", a: "Add your yarn colors, set the stripe width (fixed or random), and hit generate. Our tool creates a visual preview with per-color row breakdowns so you know exactly how much of each color you\u2019ll use." },
    { q: "What is the weighted randomizer?", a: "Assign a weight to each color to control how often it appears. Give more weight to colors you have extra yarn for (stash busting) and less to accent colors." },
    { q: "How do I avoid two of the same color next to each other?", a: "Our random and fixed modes automatically prevent consecutive same-color stripes. Only the sequence mode (A-B-C-A-B-C) follows a fixed order." },
    { q: "Can I use this for scrap yarn projects?", a: "Absolutely \u2014 that\u2019s what the weighted randomizer is for. Add all your leftover yarn colors, weight them by how much you have, and generate a balanced random pattern." },
    { q: "How many rows should each stripe be?", a: "It\u2019s personal preference. 2\u20134 rows creates a busy pattern, 6\u201310 rows creates bolder stripes. Use random widths (min/max) for a more organic, modern look." },
    { q: "Can I print or save the pattern?", a: "Yes. Use the copy button to get a text list of every stripe, or use the print button for a printable reference. You can also screenshot the visual preview." },
  ],
  "abbreviation-glossary": [
    { q: "What does SSK mean in knitting?", a: "SSK stands for Slip, Slip, Knit. It\u2019s a left-leaning decrease where you slip two stitches knitwise one at a time, then knit them together through the back loops." },
    { q: "What does SC mean in crochet?", a: "SC stands for Single Crochet (US term). In UK patterns, the same stitch is called DC (Double Crochet). This is one of the most common sources of confusion between US and UK patterns." },
    { q: "What\u2019s the difference between US and UK crochet terms?", a: "US and UK crochet terms are offset by one. A US Single Crochet = UK Double Crochet. A US Double Crochet = UK Treble. Our glossary shows both with a UK/US toggle." },
    { q: "What does FLO mean?", a: "FLO stands for Front Loop Only. Instead of working through both loops of a stitch, you insert your hook or needle through only the front loop. This creates a ridged texture." },
    { q: "How do I read a knitting pattern?", a: "Use our Pattern Translator. Paste a line from your pattern and every abbreviation gets highlighted with its full meaning. It\u2019s like a real-time dictionary for pattern instructions." },
    { q: "What does YO mean?", a: "YO stands for Yarn Over. You wrap the yarn around your needle to create a new stitch and a decorative hole. It\u2019s the foundation of lace knitting." },
  ],
  "spinning-ratio-calculator": [
    { q: "How do I calculate my spinning wheel\u2019s drive ratio?", a: "Measure the diameter of your drive wheel and the diameter of the whorl (pulley). Divide the drive wheel diameter by the whorl diameter. For example, a 22-inch wheel with a 2.5-inch whorl = 8.8:1 ratio." },
    { q: "What ratio do I need for sock yarn?", a: "Sock yarn (fingering weight) typically requires a ratio of 8:1 to 14:1 to get enough twist for durability. Higher ratios add more twist per treadle, which is what you want for strong, thin singles." },
    { q: "What is TPI in spinning?", a: "TPI stands for Twists Per Inch. It measures how many times the fiber twists in one inch of yarn. More TPI = stronger, harder yarn. Less TPI = softer, loftier yarn." },
    { q: "How much plying twist do I need?", a: "For balanced 2-ply yarn, ply at roughly 60% of your singles TPI in the opposite direction. Our calculator gives you the exact plying twist based on your singles TPI and number of plies." },
    { q: "What does scotch tension mean?", a: "Scotch tension is a braking system where a band applies friction to the bobbin. The drive band turns the flyer, and the scotch tension controls how fast the yarn winds on. It\u2019s the most common system for beginners." },
    { q: "How do I choose the right whorl?", a: "Smaller whorls = higher ratio = more twist = thinner yarn. Larger whorls = lower ratio = less twist = thicker yarn. Our reference chart matches whorl ratios to target yarn weights." },
  ],
  "cross-stitch-calculator": [
    { q: "How do I calculate the finished size of my cross stitch?", a: "Divide your pattern\u2019s stitch count by the fabric count. For example, a 150\u00D7200 stitch pattern on Aida 14 = 10.7\u00D714.3 inches. Our calculator shows the size on 10 different fabric counts at once." },
    { q: "What is the best Aida count for beginners?", a: "Aida 14 count is the most popular and beginner-friendly. The holes are easy to see, and it works with standard 2-strand floss. Aida 11 is even easier but produces larger finished pieces." },
    { q: "How much floss do I need?", a: "On average, one cross stitch uses about 1.1 inches of floss (with 2 strands). A standard DMC skein (8 meters/8.7 yards) covers roughly 430 full cross stitches. Enter your stitch count per color for an exact estimate." },
    { q: "What does stitching over two mean?", a: "On evenweave or linen fabric, each cross stitch covers 2 fabric threads instead of 1 hole. This halves the effective count: 28-count linen over two = same size as 14-count Aida." },
    { q: "How much extra fabric do I need for framing?", a: "Add at least 3 inches on each side for framing. For scroll frames or hoops, add more. Our calculator adds your chosen margin to the design dimensions automatically." },
    { q: "Can I use this for different fabric types?", a: "Yes. We support Aida (11, 14, 16, 18), Hardanger (22), evenweave (25, 28), and linen (32, 36, 40). The over-two toggle adjusts calculations for evenweave and linen." },
  ],
  "weaving-sett-calculator": [
    { q: "What is sett in weaving?", a: "Sett (also called EPI \u2014 Ends Per Inch) is the number of warp threads per inch in your fabric. The right sett depends on your yarn weight and weave structure. Too open = sleazy fabric. Too tight = stiff and warp-dominant." },
    { q: "How do I calculate sett?", a: "The standard method: wrap your yarn around a ruler for 1 inch, count the wraps (WPI), then multiply by a factor based on your weave structure. Plain weave uses 50% of WPI, twill uses 60%. Our calculator does this automatically." },
    { q: "What is loom waste?", a: "Loom waste is the unusable warp length tied to the loom. It includes the warp tied to front and back beams plus any unusable length. Typical loom waste is 18\u201336 inches depending on your loom." },
    { q: "How do I substitute a different reed?", a: "Use our Reed Substitution tab. Enter your desired EPI and your available reed dent, and we\u2019ll tell you how to thread it (e.g., alternate 1 and 2 threads per dent)." },
    { q: "How much yarn do I need for weaving?", a: "Enter your project dimensions, sett, and loom waste in our Warp Length tab. We calculate total warp and weft yardage including shrinkage allowance for your fiber type." },
    { q: "Does fiber type affect sett?", a: "Yes. Sticky fibers like wool can be sett closer because they grip each other. Slippery fibers like silk or bamboo need a tighter sett (more threads) to prevent shifting." },
  ],
  "project-cost-calculator": [
    { q: "How much does it cost to crochet a blanket?", a: "Material costs typically range from $30\u2013$150 depending on yarn quality, weight, and blanket size. Acrylic worsted for a throw runs about $40\u201360. Premium wool or cotton can be $100\u2013200+." },
    { q: "Is it cheaper to knit or buy?", a: "For simple items like scarves and hats, handmade costs are similar to store-bought. For blankets and sweaters, handmade is usually more expensive in materials alone, before counting your time. The value is in quality, customization, and the joy of making." },
    { q: "How long does it take to crochet a blanket?", a: "A throw blanket takes roughly 30\u201380 hours depending on stitch complexity and your speed. At 25 stitches per minute with worsted yarn, a basic throw takes about 50 hours." },
    { q: "What\u2019s a fair price for handmade items?", a: "A common formula: (materials \u00D7 2) + (hours \u00D7 your desired hourly rate). Our calculator shows your effective hourly rate for any selling price so you can price fairly." },
    { q: "What are notions?", a: "Notions are the non-yarn supplies for your project: buttons, zippers, stitch markers, stuffing, tapestry needles, pattern costs, etc. Add them to our calculator for a complete budget." },
    { q: "How do I estimate stitches per minute?", a: "Beginners average 15\u201320 stitches per minute. Intermediate crafters average 25\u201335. Experienced speed knitters/crocheters can hit 40+. Time yourself over 5 minutes for your personal speed." },
  ],
  "color-pooling-calculator": [
    { q: "What is color pooling?", a: "Color pooling (or planned pooling) is a technique where you use variegated yarn with a specific stitch count to make the colors stack into vertical columns, creating argyle or plaid-like patterns from a single ball of yarn." },
    { q: "How do I measure color sections?", a: "Work a swatch and count exactly how many stitches each color lasts before changing to the next. Enter these counts in order into our calculator. Accuracy here is key to successful pooling." },
    { q: "What stitch works best for color pooling?", a: "Moss stitch (SC, CH1, skip 1) is the most popular because it creates clean, consistent columns. Single crochet and linen stitch also work well." },
    { q: "Why isn\u2019t my pooling lining up?", a: "Usually it\u2019s a gauge issue. Even a slight change in tension shifts the color alignment. Try our adjust buttons (\u00B11 or \u00B12 chains) to fine-tune, or change your hook size." },
    { q: "Does every variegated yarn work for pooling?", a: "Yarn with distinct, consistent color changes works best. Short color changes (2\u20134 stitches each) pool more visibly. Long gradual transitions don\u2019t pool as cleanly." },
    { q: "How do I know how many chains to start with?", a: "Your foundation chain should equal the total number of stitches in one complete color repeat. Our calculator figures this out and shows a live preview of how the colors will stack." },
  ],
  "thread-converter": [
    { q: "How do I convert DMC to Anchor thread numbers?", a: "Type any DMC number into our search box and we\u2019ll instantly show the Anchor and Cosmo equivalents. We currently cover 80 of the most popular colors with more being added." },
    { q: "Are thread conversions exact matches?", a: "Most conversions are close matches, not identical. Different brands use different dye processes, so colors may vary slightly. Always compare threads in person for critical color matching." },
    { q: "What\u2019s the most popular embroidery thread brand?", a: "DMC is the most widely used brand worldwide, with 500 numbered colors. Anchor is popular in the UK and Europe. Cosmo is a Japanese brand known for excellent color saturation." },
    { q: "Can I search by color name?", a: "Yes. Our search works with thread numbers (e.g., \u2018310\u2019) and color names (e.g., \u2018red,\u2019 \u2018forest green\u2019). You can filter by brand to narrow results." },
    { q: "How do I convert a whole shopping list at once?", a: "Use our Bulk Convert tab. Paste a list of DMC numbers separated by commas or spaces, and we\u2019ll convert all of them in one shot with a printable results table." },
    { q: "What is the palette builder?", a: "Click the + button next to any search result to add it to your palette. The palette tab shows all your selected colors with every brand\u2019s number, ready to copy or print as a shopping list." },
  ],
  "stitch-pattern-calculator": [
    { q: "What is a stitch multiple?", a: "A stitch multiple is the number of stitches in one complete repeat of a pattern. If a pattern says \"multiple of 6,\" your total stitch count must be divisible by 6 for the pattern to work evenly." },
    { q: "What does \"multiple of 4 plus 1\" mean?", a: "The \"plus\" value is an extra stitch needed for edge symmetry. \"Multiple of 4 plus 1\" means counts like 5, 9, 13, 17 — any number divisible by 4 with 1 added." },
    { q: "What is the LCM and why does it matter?", a: "LCM (Least Common Multiple) is the smallest number all your pattern multiples divide into evenly. It determines the spacing between compatible stitch counts. A smaller LCM gives you more width options." },
    { q: "Can I combine stitches with different multiples in a sampler blanket?", a: "Yes — that is exactly what a sampler blanket is. The key is finding a stitch count that works for every pattern. Our calculator finds all compatible counts within your desired range." },
    { q: "What if no stitch count works for all my patterns?", a: "This usually happens when plus values conflict. Try swapping one pattern for a similar one with a different plus value, or adjust your edge stitch count. Sometimes adding 1 edge stitch solves the conflict." },
    { q: "How many rows do I need for a complete stitch repeat?", a: "It depends on the stitch. Simple stitches need 1 row. Waffle stitch needs 4. Celtic weave needs 4. Always complete full repeats so your pattern does not get cut off mid-repeat." },
    { q: "How do I use the crochet stitch calculator?", a: "Select the stitch patterns you want to combine, enter each pattern\u2019s stitch multiple and offset (e.g., multiple of 6 + 1), and the calculator finds all compatible stitch counts within your desired range. Choose the count closest to your target width." },
    { q: "What is gauge in crochet?", a: "Gauge is the number of stitches and rows per inch in your crocheted fabric. It depends on your hook size, yarn weight, and personal tension. Knowing your gauge lets you calculate the exact stitch count needed for a specific width." },
    { q: "How do I convert between yarn weights?", a: "Use the Yarn Weight Chart to compare CYC categories (0\u20137) across US, UK, and Australian naming systems. Each weight has a recommended gauge range and hook size. Substituting between adjacent weights may work with a hook size adjustment, but always swatch first." },
  ],
  "stitch-quick-reference": [
    { q: "How many yarn overs are in a double crochet?", a: "A double crochet uses 4 total yarn overs: 1 before inserting the hook, 1 when pulling up the loop, and 2 more during the two pull-through-2 steps. The initial YO before inserting is what gives DC its height." },
    { q: "What is the turning chain for each crochet stitch?", a: "SC = 1 chain, HDC = 2 chains, DC = 3 chains, TR = 4 chains, DTR = 5 chains. The turning chain number matches the stitch height." },
    { q: "What is the difference between front post and regular double crochet?", a: "The only difference is where you insert the hook. Regular DC goes into the top loops. Front post DC (FPdc) goes around the vertical post of the stitch below. The yarn overs and pull-throughs are identical." },
    { q: "Why does HDC feel different from other stitches?", a: "HDC is the one exception to the crochet pattern. Instead of pulling through 2 loops repeatedly, you pull through all 3 loops at once. This gives it a distinctive third horizontal bar at the top." },
    { q: "What is the difference between SSK and K2tog?", a: "Both reduce 2 stitches to 1. K2tog leans right — insert through 2 stitches and knit. SSK leans left — slip 2 knitwise, then knit together through back loops. Use them as mirrors for symmetrical shaping." },
    { q: "How do I count loops on my hook to check for mistakes?", a: "After pulling up a loop: SC has 2 loops, HDC has 3, DC has 3, TR has 4. Each pull-through-2 step removes one loop. If your count is wrong, you missed a yarn over or pulled through too many." },
  ],
  "uk-to-us-converter": [
    { q: "What is the difference between UK and US crochet terms?", a: "UK terms are shifted one position up from US terms. A UK double crochet equals a US single crochet, a UK treble equals a US double crochet, and so on." },
    { q: "Does this converter work with abbreviations?", a: "Yes. It converts both full terms (double crochet → single crochet) and abbreviations (dc → sc)." },
    { q: "Can I convert US patterns to UK?", a: "Yes — use the US → UK toggle at the top to reverse the direction." },
    { q: "Does it handle vintage or old-fashioned terms?", a: "Yes. Terms like wool over, wool forward, and cast off from vintage patterns are included." },
    { q: "Is my pattern text sent to a server?", a: "No. All conversion happens in your browser. Nothing is uploaded or stored." },
  ],
  "circle-calculator": [
    { q: "Why is my circle turning into a hexagon?", a: "Increases are stacking on top of each other round after round. This calculator staggers increases to prevent that." },
    { q: "My circle is cupping into a bowl shape. What do I do?", a: "Your tension is too tight. Try going up one hook size, or add 1-2 extra increases per round." },
    { q: "Can I use this for hats?", a: "Yes! A hat crown is a flat circle. Follow this pattern for the top, then stop increasing and work even rounds for the sides." },
    { q: "How big will my circle be?", a: "That depends on your yarn weight and gauge. A 10-round single crochet circle in worsted weight is roughly 5-6 inches across." },
    { q: "Do I have to use a magic ring to start?", a: "No. You can chain 2 and work 6 single crochets into the second chain from the hook instead. The magic ring method closes the center hole more neatly, but the chain method works just as well and is easier for beginners." },
  ],
  "needle-guide": [
    { q: "What needle should I use to weave in crochet ends?", a: "A tapestry needle (also called a yarn needle). The blunt tip slides between stitches without splitting your yarn." },
    { q: "What is the difference between a tapestry needle and a chenille needle?", a: "Both have large eyes, but a tapestry needle has a blunt tip while a chenille needle is sharp. Use tapestry for yarn work, chenille for piercing tightly woven fabric." },
    { q: "Can I use a regular sewing needle for crochet?", a: "You can in a pinch, but the small eye makes threading yarn difficult and the sharp tip will split your stitches. A tapestry needle is much easier." },
    { q: "What needle do I need to add beads to my crochet?", a: "A beading needle. They are thin enough to fit through seed bead holes. Pre-string your beads onto the yarn before you start crocheting." },
    { q: "What size tapestry needle should I use for different yarn weights?", a: "Match needle eye size to your yarn thickness. For lace and fingering weight, use a size 18–20 tapestry needle. For DK and worsted, a size 14–16 works well. For bulky and super bulky yarn, use a size 13 or larger. The needle should thread easily without bending the yarn." },
  ],
  "cast-on-calculator": [
    { q: "How many stitches do I cast on for a specific width?", a: "Divide your gauge stitches by the gauge measurement to get stitches per inch, then multiply by your desired width. For example, 18 stitches over 4 inches = 4.5 stitches per inch. For a 50-inch blanket, that\u2019s 225 stitches." },
    { q: "What is a stitch pattern multiple?", a: "Many stitch patterns repeat over a fixed number of stitches. If your pattern repeats every 6 stitches, your cast-on count must be a multiple of 6. Our calculator rounds UP to the nearest multiple so your pattern fits evenly." },
    { q: "Do I need to add edge stitches?", a: "If you\u2019re knitting flat pieces that will be seamed, most knitters add 1\u20132 selvedge stitches per side. These stitches get absorbed into the seam and don\u2019t affect the finished width of your project." },
    { q: "How do I figure out my gauge?", a: "Knit a swatch at least 6 inches wide. Lay it flat, measure 4 inches across the center (avoiding edges), and count the stitches. That\u2019s your gauge over 4 inches." },
    { q: "Why does my finished width not match?", a: "Gauge can shift between a small swatch and a large project, especially on circular needles vs flat. Blocking also changes dimensions. Always measure as you go and adjust if needed." },
  ],
  "hat-calculator": [
    { q: "How do I know what size hat to knit?", a: "Measure around the widest part of the head, just above the ears and eyebrows. Use our size chart to match the measurement to a standard size, or enter the exact circumference for a custom fit." },
    { q: "What is negative ease in a hat?", a: "Negative ease means the hat is intentionally smaller than the head circumference so it stretches to fit snugly. Stockinette gets 10% negative ease, ribbing 15% (more stretch), and colorwork 5% (less stretch)." },
    { q: "Why round the cast on to a multiple of 8?", a: "An 8-point crown decrease divides the stitches into 8 equal sections. Each section decreases by 1 stitch every other round until 8 stitches remain. Rounding to a multiple of 8 ensures even, symmetrical decreases." },
    { q: "How long should my hat be before I start crown decreases?", a: "Work even rounds until the hat reaches the top of the wearer\u2019s ears. Check our height chart for standard measurements by size: 5 inches for a newborn up to 9.5 inches for a large adult." },
    { q: "How much yarn do I need for a hat?", a: "In worsted weight yarn, baby hats need 50\u2013100 yards, child hats need 100\u2013150 yards, and adult hats need 150\u2013250 yards. Thicker yarn uses more yardage per area; thinner yarn uses less." },
    { q: "Can I use this for crochet hats?", a: "The cast-on count and sizing work for crochet too. However, the crown decrease schedule is written in knitting terms (K2tog). For crochet, work decreases (sc2tog or dc2tog) evenly in each decrease round using the same section count." },
  ],
  "amigurumi-shapes": [
    { q: "What hook size should I use for amigurumi?", a: "Use a hook 1-2 sizes smaller than your yarn label recommends. This creates a tighter fabric that holds stuffing without showing through." },
    { q: "Do I need to join rounds in amigurumi?", a: "No. Most amigurumi is worked in continuous spirals without joining or turning chains. Use a stitch marker to track round starts." },
    { q: "How do I make a bigger sphere?", a: "Increase the number of rounds. More increase rounds before the even section creates a wider sphere. You can also use thicker yarn." },
    { q: "What is sc2tog?", a: "Single crochet two together — a decrease. Insert hook in next stitch, pull up a loop, insert in following stitch, pull up a loop, yarn over and pull through all 3 loops." },
    { q: "How do I close the last round of amigurumi neatly?", a: "After working all decrease rounds until about 6 stitches remain, stuff the piece firmly. Cut the yarn leaving a 6-inch tail, thread it onto a tapestry needle, and slip through the front loops of the remaining stitches one at a time. Pull tight to close the hole and weave the tail through several stitches on the inside to secure." },
  ],
  "wpi-calculator": [
    { q: "What is WPI (wraps per inch)?", a: "WPI stands for Wraps Per Inch. You wrap yarn around a ruler for exactly one inch and count the number of wraps. It\u2019s the most reliable way to identify the weight of unlabeled yarn." },
    { q: "How do I measure WPI accurately?", a: "Wrap your yarn snugly around a ruler or dowel for one inch. Don\u2019t stretch the yarn or leave gaps, and don\u2019t overlap strands. Count the number of wraps. Repeat in 2\u20133 spots and average the results." },
    { q: "Why does my WPI fall between two yarn weights?", a: "WPI ranges overlap between adjacent weights. A yarn at 12 WPI could be Fine/Sport or Medium/Worsted. The best way to confirm is to knit or crochet a gauge swatch and compare your stitch count to the standard ranges." },
    { q: "Can I use WPI for textured or novelty yarn?", a: "Textured yarns like boucl\u00E9, chenille, or eyelash yarn don\u2019t wrap evenly, so WPI measurements are less reliable. For these yarns, swatching is the best way to determine the effective weight." },
    { q: "What tools do I need to measure WPI?", a: "A standard ruler works fine. You can also use a dedicated WPI tool (a notched card or gauge), a pencil, or a dowel. Any straight, smooth surface about \u00BC inch in diameter works." },
    { q: "How does WPI relate to the CYC yarn weight system?", a: "The Craft Yarn Council\u2019s 0\u20137 weight categories correspond to WPI ranges. For example, worsted (CYC 4) is typically 9\u201312 WPI. Our converter maps your WPI to the matching CYC category with needle, hook, and gauge recommendations." },
  ],
  "c2c-calculator": [
    { q: "What is C2C crochet?", a: "C2C (corner-to-corner) is a crochet technique where you build a blanket diagonally. You start with one block in a corner, increase one block per row until you reach the widest diagonal, then decrease back down to the opposite corner." },
    { q: "How do I measure a C2C gauge swatch?", a: "Crochet a swatch of at least 5\u00D75 blocks. Measure the total width and height in inches, then divide by the number of blocks. C2C blocks are often not square, so measure both directions." },
    { q: "What is a diagonal row in C2C?", a: "Each diagonal row runs from one edge of the blanket to the other at a 45-degree angle. The total number of diagonal rows equals blocks wide + blocks tall \u2013 1. This tells you how many rows you\u2019ll work from start to finish." },
    { q: "How do I estimate yardage for a C2C blanket?", a: "Unravel one completed block and measure the yarn length in inches. Enter that number in the \u2018yarn per block\u2019 field. The calculator multiplies by total blocks, converts to yards, and adds a 10% buffer." },
    { q: "Can I make a rectangular C2C blanket?", a: "Yes. C2C works for any rectangle. You increase diagonally until you reach the shorter side\u2019s block count, then work even rows (increasing one end, decreasing the other) until you reach the longer side, then decrease to the final corner." },
    { q: "How do I add a border to a C2C blanket?", a: "Most crafters add a simple SC or DC border after completing the C2C panel. Subtract your planned border width from the target dimensions before calculating block counts, so the finished blanket (panel + border) hits your target size." },
  ],
  "sock-calculator": [
    { q: "How do I measure my foot for sock knitting?", a: "Measure the circumference around the ball of your foot (widest part) and the length from the back of your heel to the tip of your longest toe. The calculator applies 10% negative ease so socks fit snugly." },
    { q: "What is negative ease in socks?", a: "Negative ease means the sock is slightly smaller than your actual foot measurement. The standard is 10% \u2014 so an 8-inch foot circumference gets a 7.2-inch sock. The stretch of knit fabric makes it fit comfortably without sagging." },
    { q: "What is the difference between top-down and toe-up socks?", a: "Top-down socks start at the cuff and work down to the toe, using a heel flap and gusset. Toe-up socks start at the toe and work up, typically using a short-row heel. Both produce great socks \u2014 it is mostly personal preference." },
    { q: "What gauge should I use for sock yarn?", a: "Most sock yarn (fingering weight) knits at 28\u201336 stitches per 4 inches on US 1\u20133 (2.25\u20133.25mm) needles. A tighter gauge creates a denser, more durable fabric. Always swatch with your specific yarn." },
    { q: "Why does the cast on need to be a multiple of 4?", a: "Socks are knit in the round, typically on 4 double-pointed needles or in 2 halves on magic loop. A multiple of 4 ensures even stitch distribution and makes K2P2 ribbing work evenly." },
    { q: "What is Kitchener stitch?", a: "Kitchener stitch (grafting) is a sewing technique that joins two sets of live stitches invisibly. It is used to close the toe of top-down socks, creating a smooth, flat seam with no ridge." },
  ],
  "granny-square-planner": [
    { q: "How many granny squares do I need for a throw blanket?", a: "For a standard throw (50\u00D760 inches) using 6-inch squares, you need 8 across \u00D7 10 tall = 80 squares. Use our calculator to get the exact count for any blanket size and square size." },
    { q: "How much yarn does one granny square use?", a: "A classic 6-inch granny square in worsted weight uses roughly 15\u201320 yards. A 12-inch afghan square uses 40\u201360 yards. The exact amount depends on your yarn weight, hook size, and number of rounds." },
    { q: "How do I join granny squares?", a: "Common methods include whip stitch, mattress stitch, slip stitch join, and join-as-you-go. Our calculator estimates joining yarn based on 1.5\u00D7 the perimeter of each square with a 10% buffer." },
    { q: "What is the best size for granny squares?", a: "6-inch squares are the most popular \u2014 they are big enough to show pattern detail but small enough to be portable. Use 4-inch for scrap projects, 8-inch for faster progress, or 12-inch for sampler blankets." },
    { q: "How do I make sure all my granny squares are the same size?", a: "Block every square before joining. Pin each square to a blocking mat at the target size, mist with water, and let dry. This evens out tension differences and makes joining much easier." },
    { q: "Can I mix different granny square patterns in one blanket?", a: "Absolutely \u2014 that is a sampler blanket. The key is making sure every square finishes at the same size. Block each square to your target dimensions before joining." },
  ],
  "sleeve-calculator": [
    { q: "How do I calculate sleeve decreases?", a: "Measure your upper arm and wrist circumference, multiply each by your stitch gauge, then divide the difference by 2 (since you decrease at both ends). Our calculator distributes those decrease events evenly across the available shaping rows." },
    { q: "What does 'decrease 1 st each end' mean?", a: "It means you work one decrease at the beginning of the row and one at the end. In knitting, that\u2019s typically SSK at the start and K2tog at the end of a right-side row. In crochet, SC2tog at both ends." },
    { q: "Why is there a 1-inch buffer at each end?", a: "The top inch allows a smooth transition from the body join to the start of shaping. The bottom inch provides a flat section above the cuff ribbing so the last decrease isn\u2019t right next to the ribbing." },
    { q: "Can I use this for set-in sleeves?", a: "This calculator is designed for straight tapered sleeves (top-down or bottom-up). Set-in sleeves require a shaped sleeve cap with short rows, which involves different math." },
    { q: "What if the remainder is not zero?", a: "When decreases don\u2019t divide evenly, the calculator splits them into two groups: some worked every N rows and the rest every N+1 rows. This distributes the shaping smoothly instead of bunching it." },
  ],
  "raglan-calculator": [
    { q: "What is a raglan sweater?", a: "A raglan sweater has diagonal seam lines running from the neckline to the underarm. It\u2019s typically knit top-down in one piece, starting at the neck and increasing outward until the body and sleeves are separated at the underarm." },
    { q: "How are stitches distributed in a raglan?", a: "A standard raglan distributes stitches as roughly 30% back, 30% front, 15% each sleeve, plus 4 raglan seam stitches (1 at each of the 4 raglan lines). This calculator uses that standard ratio." },
    { q: "How many stitches do I increase per round?", a: "Each increase round adds 8 stitches total \u2014 2 stitches at each of the 4 raglan lines (one on each side of the raglan marker). You increase every other round." },
    { q: "What happens at the underarm?", a: "When the yoke is complete, you separate the body and sleeves. Place sleeve stitches on waste yarn or holders, then cast on 2\u20136 stitches at each underarm gap to bridge the body sections." },
    { q: "How much ease should I add?", a: "For a standard fit, add 2\u20134 inches of positive ease to your actual chest measurement. For a relaxed or oversized fit, add 4\u20138 inches. Enter the total desired circumference (body + ease) into the calculator." },
    { q: "Does this work for crochet raglans?", a: "Yes. The stitch math is the same. Instead of knit increases (KFB or M1), use crochet increases (2 SC or 2 DC in the same stitch) at each raglan point." },
  ],
  "blocking-calculator": [
    { q: "What is blocking in knitting and crochet?", a: "Blocking is the process of wetting or steaming a finished piece and pinning it to specific dimensions so it dries in the correct shape. It evens out stitches, opens up lace patterns, and gives your work a polished, professional finish." },
    { q: "Do I have to block every project?", a: "Not strictly, but blocking dramatically improves the appearance of most projects. Lace absolutely must be blocked to open up the pattern. Garments block for better fit and drape. Blankets and scarves benefit from evening out tension." },
    { q: "Can I steam block acrylic yarn?", a: "NEVER steam acrylic. Heat permanently alters acrylic fibers — they lose their bounce and become flat and lifeless. This is called 'killing' the yarn and cannot be undone. Use spray or cool wet blocking only for acrylic." },
    { q: "How long does blocking take to dry?", a: "Wet blocked items typically take 12–48 hours depending on thickness, humidity, and air circulation. Spray blocked items dry faster, usually 6–24 hours. Never unpin until fully dry or the piece will spring back." },
    { q: "How much can I stretch a piece during blocking?", a: "Natural fibers like wool can stretch 15–30% when blocking lace. For stockinette, 5–15% is realistic. Synthetic fibers resist stretching and rarely hold more than 5%. The calculator shows feasibility ratings for your specific stretch percentages." },
    { q: "What equipment do I need for blocking?", a: "At minimum: interlocking foam mats, rustproof T-pins or blocking pins, and a spray bottle or basin. Blocking wires are helpful for straight edges. Wool wash like Eucalan or Soak is recommended for wet blocking." },
  ],
  "stash-estimator": [
    { q: "How do I weigh a partial skein?", a: "Use a kitchen scale that measures in grams. Place the partial skein on the scale. If the yarn is on a project, weigh the project and subtract the estimated weight of your work, or wind off the remaining yarn and weigh it separately." },
    { q: "How accurate is the partial skein estimate?", a: "It is quite accurate for commercial machine-spun yarn with consistent thickness. Handspun or art yarns with thick-and-thin sections may vary. The estimate is based on the proportion of weight remaining compared to a full skein." },
    { q: "What if I do not have the original ball band?", a: "Use the yardage reference table. Identify the yarn weight by WPI or visual comparison, then use the typical yardage per 100g value for that weight category. Our WPI Calculator can help identify the weight." },
    { q: "Why does fiber content affect the estimate?", a: "Different fibers have different densities. Cotton is heavier per yard than wool, so a 50g ball of cotton has fewer yards than a 50g ball of wool at the same thickness. The weight-based formula assumes the same fiber as the original skein." },
    { q: "Can I use this for cakes and hanks?", a: "Yes. The formula works for any yarn put-up — skeins, balls, cakes, or hanks. You need the full weight and yardage from the label, plus the current weight of your partial amount." },
    { q: "How do I identify unlabeled yarn weight?", a: "Measure wraps per inch by wrapping yarn snugly around a ruler. 14+ WPI is fingering, 11–12 is DK, 9–10 is worsted, 6–8 is bulky. Our WPI Calculator gives a detailed breakdown with needle and hook recommendations." },
  ],
};
