export interface FAQ {
  q: string;
  a: string;
}

export const toolFaqs: Record<string, FAQ[]> = {
  "yarn-calculator": [
    { q: "How does the yarn calculator estimate a flat project?", a: "It divides target area by representative swatch area, multiplies by the yarn length measured from that swatch, and then applies only the allowance percentage shown in the form." },
    { q: "What kind of project can I enter?", a: "The model covers flat rectangular fabric. It does not model garments, shaping, sleeves, seams, borders, fringe, or three-dimensional pieces. Estimate those separately or use construction-specific pattern quantities." },
    { q: "How do I calculate whole skeins?", a: "Enter the length and weight printed on the exact yarn label. The calculator divides planned length by length per skein and rounds up, then reports the corresponding whole-skein weight." },
    { q: "Does yarn weight or stitch pattern change the calculation?", a: "The yarn-weight and craft selectors filter optional pattern suggestions only. The estimate changes when the measured swatch consumption, target dimensions, or explicit allowance changes." },
    { q: "Is the default 10 percent allowance a requirement?", a: "No. It is an editable planning input shown separately from measured consumption. Choose an allowance for the actual project and account for borders, seams, shaping, tails, color proportions, and rejected material outside the flat-area model." },
    { q: "How does the leftover-yarn calculator work?", a: "It scales the labeled full-skein length by partial weight divided by labeled full-skein weight. The yarn remnant must weigh more than zero and no more than the full skein, with the label, cone, or core excluded." },
  ],
  "needle-converter": [
    { q: "What size knitting needles should I use?", a: "Check your yarn label for the recommended needle size. Our converter shows the equivalent size across US, metric (mm), UK, and Japanese systems so you can match any pattern regardless of origin." },
    { q: "How do I convert US needle sizes to mm?", a: "US sizes don\u2019t follow a linear scale. For example, US 6 = 4.0mm, US 7 = 4.5mm, US 8 = 5.0mm. Our converter handles all 23 sizes from US 0 (2.0mm) to US 50 (25.0mm)." },
    { q: "What size crochet hook do I need?", a: "It depends on your yarn weight. Lace yarn uses 1.5\u20132.25mm hooks, worsted uses 5.0\u20136.0mm hooks, and bulky uses 6.5\u20139.0mm hooks. Our chart shows recommendations for every weight." },
    { q: "Are UK and US needle sizes the same?", a: "No. UK sizes run backwards, a UK 14 is 2.0mm (tiny) while a US 14 is 10.0mm (large). Our converter prevents this common confusion by showing all systems side by side." },
    { q: "What\u2019s the difference between US and metric crochet hooks?", a: "US crochet hooks use letter sizes (B through S) while metric uses millimeters. For example, US H/8 = 5.0mm. Our converter maps all 24 common hook sizes across both systems." },
    { q: "Can I substitute a different needle size?", a: "Yes, but it will change your gauge. Going up a size creates a looser, drapier fabric. Going down creates a tighter, firmer fabric. Always swatch first when substituting." },
    { q: "What size knitting needle do I need for worsted weight?", a: "Worsted weight yarn (CYC category 4) typically uses US 7\u20139 needles (4.5\u20135.5mm). The exact size depends on the pattern and your personal tension. Check your pattern for the recommended size, then swatch to confirm your gauge matches." },
    { q: "How do I convert US needle sizes to metric?", a: "US needle sizes don\u2019t follow a linear scale. Common conversions: US 4 = 3.5mm, US 6 = 4.0mm, US 7 = 4.5mm, US 8 = 5.0mm, US 10 = 6.0mm, US 15 = 10.0mm. Use our converter for the complete chart of all 23 sizes." },
    { q: "What needle size is best for beginners?", a: "US 8 (5.0mm) needles with worsted weight yarn are the most beginner-friendly combination. The stitches are large enough to see clearly and count easily, and worsted is the most widely available yarn weight with the most pattern options." },
  ],
  "gauge-calculator": [
    { q: "What does the swatch mode calculate?", a: "It divides the stitch and row counts you enter by the measured width and height, then displays the equivalent count per 4 inches or 10 centimeters." },
    { q: "Does scaling one count resize a whole pattern?", a: "No. The count scaler applies a gauge ratio only to the stitch or row counts you enter. It does not regrade shaping, construction, pattern repeats, yarn quantity, or fit." },
    { q: "What happens if I enter only part of a row calculation?", a: "The tool asks you to complete the pattern row gauge, your row gauge, and the pattern row count together. It does not present an unchanged row count as a calculated result." },
    { q: "How does target-width rounding work?", a: "The target-width mode rounds upward to a whole stitch, then upward again when needed to satisfy the entered multiple-plus constraint. It displays the modeled width so you can review the effect." },
    { q: "Do edge stitches or turning chains come from the calculator?", a: "No. Those are optional additions you enter from the selected pattern. Whether turning chains count as stitches and how edges are constructed are pattern-specific decisions." },
  ],
  "yarn-weight-chart": [
    { q: "What are the yarn weight categories?", a: "The Craft Yarn Council lists 0 (Lace), 1 (Super Fine), 2 (Fine), 3 (Light), 4 (Medium), 5 (Bulky), 6 (Super Bulky), and 7 (Jumbo). Its gauge and tool-size ranges are guidelines, not guarantees for a particular yarn or project." },
    { q: "What is DK weight yarn?", a: "DK, or double knitting, is included in CYC category 3 (Light). The knitting guideline is 21–24 stockinette stitches per 4 inches on 3.75–4.5 mm needles (US 5–7). Australian 8-ply is a common approximate name; verify the actual label and swatch." },
    { q: "Can I substitute DK for worsted weight?", a: "Possibly, but the labels alone cannot answer that. DK and worsted are in adjacent CYC categories. Swatch with the actual yarn in the pattern's stitch pattern and check stitch gauge, row gauge, and fabric. The checker does not calculate compatibility scores or a required needle-size change." },
    { q: "What does ply mean in yarn?", a: "Ply can mean the strands twisted together, while names such as 4-ply or 8-ply also serve as regional weight labels. Those labels are approximate and do not necessarily describe the actual strand count or establish an exact CYC category." },
    { q: "What\u2019s the difference between UK and US yarn terms?", a: "Names such as fingering, 4-ply, DK, worsted, and aran are used differently across markets and manufacturers. The chart gives common approximate associations, not exact conversions. Compare label guidance and swatch before substituting." },
    { q: "How do I find the weight of unlabeled yarn?", a: "Wraps per inch can suggest possible categories, but CYC's ranges overlap and wrapping tension affects the result. Wrap without stretching or overlapping, compare the guidance, then verify with a swatch. A WPI measurement alone cannot confirm a substitution." },
    { q: "Can I substitute any yarn for another?", a: "Matching categories or yards per gram does not establish interchangeability. Swatch in the intended stitch pattern, follow the yarn's care instructions, and compare gauge and fabric with the pattern's requirements. Even matching gauge does not guarantee the same feel or drape." },
    { q: "What happens if I use a different fiber?", a: "Fiber content and yarn construction can change elasticity, drape, texture, and care requirements. Check the actual yarn labels and evaluate a washed and dried swatch according to their care instructions instead of assuming all yarns of one fiber behave alike." },
    { q: "How do I adjust my pattern for a yarn substitution?", a: "Start with the pattern's suggested tools and make a swatch in its stitch pattern. Compare stitch and row gauge and decide whether the fabric suits the project. Try another tool size or yarn and swatch again if needed; matching gauge alone is not enough. Recheck yarn quantity using label information and measured swatch use." },
  ],
  "stitch-counter": [
    { q: "How do I count stitches while knitting?", a: "Use our digital stitch counter. Tap the + button after each row or repeat. The large display is designed for one-handed use while your other hand holds your work." },
    { q: "Can I track multiple counters at once?", a: "Yes, you can run up to 6 independent counters simultaneously. Name each one (e.g., \u2018rows,\u2019 \u2018pattern repeats,\u2019 \u2018decreases\u2019) and track them all on one screen." },
    { q: "Will my count save if I close the browser?", a: "The counter attempts to save in this browser profile\u2019s local storage, so it can return after closing the tab on the same browser and device. It does not sync to another browser or device, and the saved state can be unavailable or lost if storage is blocked, cleared, or reset. Keep a separate note when the count matters." },
    { q: "What are row reminders?", a: "Set a reminder at one exact count with a note (e.g., \u2018Row 12: start decreases\u2019). Reminders are checked only when the first counter reaches that count. They do not create a repeating interval or attach independently to every counter." },
    { q: "Is there an undo button?", a: "Yes. Count changes, including the per-counter reset, use a 50-action undo/redo history. The Settings action that resets all counters clears that history." },
    { q: "Can I use this on my phone?", a: "The responsive counter uses large tap targets. Its fullscreen control requests the browser's full-screen view, but browser support and permissions determine whether that request succeeds." },
  ],
  "blanket-calculator": [
    { q: "How big should a throw blanket be?", a: "The calculator uses 50\u00D760 inches (127\u00D7152cm) as a common throw planning preset. Measure the intended recipient or space, or follow the pattern dimensions, before buying yarn." },
    { q: "How many chains do I need for a throw blanket?", a: "It depends on your yarn weight and gauge. With worsted yarn at 4 stitches per inch, a 50-inch throw needs about 200 chains. Enter your exact gauge into our calculator for a precise number with stitch multiple rounding." },
    { q: "How much yarn do I need for a baby blanket?", a: "There is no single reliable amount for every baby blanket. Enter the intended dimensions and weigh a swatch made with the actual yarn and stitch pattern to calculate yards and skeins." },
    { q: "What is pillow tuck?", a: "Pillow tuck adds extra length (about 20 inches) to the top of a bed blanket so it can fold over the pillows for a finished look. Toggle it on in our calculator for bed-sized blankets." },
    { q: "How do I calculate overhang for a bed blanket?", a: "Measure from the mattress edge to the point where you want the blanket to end. Enter that chosen drop; the calculator adds it to both sides of the width and to the foot of the length." },
    { q: "How many skeins do I need?", a: "Enter the swatch dimensions and grams used plus the length and weight printed on the yarn label. The calculator scales the swatch consumption to the finished area, adds a displayed 10% buffer, and rounds up to whole skeins." },
  ],
  "increase-decrease-calculator": [
    { q: "How does the calculator distribute one-pass increases?", a: "It models KFB or two single crochets in one source stitch. It subtracts one consumed source stitch per increase, then distributes the unchanged source stitches across the change events and verifies the target count." },
    { q: "What changes between a flat row and in-the-round result?", a: "A flat row distributes unchanged stitches across two edge gaps and the gaps between changes. A round uses circular gaps before each change with no separate finish edge. Markers, right-side rows, and visual shaping remain pattern-specific." },
    { q: "How does the calculator distribute decreases?", a: "It models non-overlapping K2tog or SC2tog changes. Each decrease consumes two source stitches and produces one; the helper accounts for both before distributing unchanged stitches." },
    { q: "Does this choose the best increase or decrease method?", a: "No. The displayed methods make the count arithmetic explicit. Follow the pattern when it specifies another method, lean, placement, or edge treatment." },
    { q: "What if the unchanged stitches do not divide evenly?", a: "The group sizes differ by at most one while the helper preserves the exact starting and target counts. Numerical balance does not guarantee a particular fabric appearance." },
    { q: "Can it plan changes across several rows or rounds?", a: "No. It models one row or round only. A multi-row shaping schedule needs a construction-specific plan." },
  ],
  "stripe-generator": [
    { q: "What does the stripe generator calculate?", a: "It creates a bounded sequence of palette colors and whole row counts, then reports each color's share of generated rows. It does not calculate yarn use." },
    { q: "What is a relative color weight?", a: "In random and fixed-row modes, a larger whole-number weight makes a color more likely among eligible colors. It is not a yardage amount, percentage, or exact final share." },
    { q: "How do I avoid two of the same color next to each other?", a: "Our random and fixed modes automatically prevent consecutive same-color stripes. Only the sequence mode (A-B-C-A-B-C) follows a fixed order." },
    { q: "Can it prove my leftovers are sufficient?", a: "No. Measure the yarn available and the per-color use of a representative repeat separately. Row share alone does not establish yarn share." },
    { q: "How are stripe widths chosen?", a: "Random-width mode samples an inclusive whole-number range. Fixed-row and palette-sequence modes use one whole row count for every stripe." },
    { q: "Can I save the row plan?", a: "Use the copy control to copy the generated text. The page does not promise durable cloud storage or a print service." },
  ],
  "abbreviation-glossary": [
    { q: "What does SSK mean in knitting?", a: "SSK stands for Slip, Slip, Knit. It\u2019s a left-leaning decrease where you slip two stitches knitwise one at a time, then knit them together through the back loops." },
    { q: "What does SC mean in crochet?", a: "SC stands for Single Crochet (US term). In UK patterns, the same stitch is called DC (Double Crochet). This is one of the most common sources of confusion between US and UK patterns." },
    { q: "What\u2019s the difference between US and UK crochet terms?", a: "US and UK crochet terms are offset by one. A US Single Crochet = UK Double Crochet. A US Double Crochet = UK Treble. Our glossary shows both with a UK/US toggle." },
    { q: "What does FLO mean?", a: "FLO stands for Front Loop Only. Instead of working through both loops of a stitch, you insert your hook or needle through only the front loop. This creates a ridged texture." },
    { q: "How do I read a knitting pattern?", a: "Use our Pattern Translator. Paste a line from your pattern and every abbreviation gets highlighted with its full meaning. It\u2019s like a real-time dictionary for pattern instructions." },
    { q: "What does YO mean?", a: "YO stands for Yarn Over. You wrap the yarn around your needle to create a new stitch and a decorative hole. It\u2019s the foundation of lace knitting." },
  ],
  "spinning-ratio-calculator": [
    { q: "How do I calculate my spinning wheel\u2019s drive ratio?", a: "Prefer the maker's published ratio or effective diameters. Otherwise measure the drive-band contact path on both wheels in the same unit and divide the drive-wheel value by the connected-pulley value. Do not substitute an outside flange diameter." },
    { q: "Does this result always describe flyer rotations?", a: "No. The driven component depends on the wheel design. Consult the wheel manual to determine whether the measured pulley drives the flyer or bobbin, especially on bobbin-led and double-drive systems." },
    { q: "Why can the actual ratio differ from the calculation?", a: "The formula describes ideal pulley geometry. Measuring an outer flange instead of the effective band path, along with drive-band condition, tension, slip, setup, and measurement error, can change the observed result." },
    { q: "Can this calculator tell me twists per inch or yarn weight?", a: "No. Pulley ratio alone does not determine twists per inch, yarn weight, strength, take-up, or plying balance. Those outcomes depend on operation, drafting, fiber preparation, and the finished sample." },
    { q: "How should I compare pulley settings?", a: "Use only settings your wheel manual identifies as compatible. Record the full setup, make and finish a sample, then compare that sample before scaling up." },
  ],
  "cross-stitch-calculator": [
    { q: "How do I calculate the finished size of my cross stitch?", a: "Divide the pattern stitch count by effective stitches per inch. Effective count equals the fabric grid count divided by whether each full cross spans one or two intervals." },
    { q: "Does the calculator choose a fabric or strand count?", a: "No. Use the pattern, exact product guidance, desired coverage, and a sample to choose them. The calculator only applies the values you enter." },
    { q: "How does the floss planning model work?", a: "It models two ideal front diagonals per full cross, then applies the working strands, allowance, labeled skein length, and bundle-strand count you enter. It is not an exact consumption prediction." },
    { q: "What does stitching over two mean?", a: "On evenweave or linen fabric, each cross stitch covers 2 fabric threads instead of 1 hole. This halves the effective count: 28-count linen over two = same size as 14-count Aida." },
    { q: "How much extra fabric do I need for framing?", a: "Confirm a positive per-side margin with the intended frame, hoop, edge finish, and seller. The calculator adds the amount you enter twice to each design dimension." },
    { q: "Can I use over two on any listed fabric?", a: "The arithmetic applies the selected span consistently to any entered grid count. Whether that stitching method is appropriate for the actual fabric is a project decision." },
  ],
  "weaving-sett-calculator": [
    { q: "What is sett in weaving?", a: "Sett, expressed as ends per inch (EPI), is the number of warp ends across one inch. Yarn, structure, beat, intended hand, and wet finishing all affect a useful sett, so the displayed value is a sampling starting point rather than a final answer." },
    { q: "How does this calculator estimate a starting sett?", a: "It applies WPI \u00d7 warp threads in one repeat \u00f7 (interlacements plus warp threads) for the supported plain-weave and 2/2-twill structures. Generic structure labels without a defined repeat are not assigned a universal factor." },
    { q: "What does the warp worksheet include?", a: "It uses the entered width at reed, planned woven length, EPI, loom-waste and sampling lengths, explicit length allowance, and optional yards-per-skein value. The provisional weft quantity assumes PPI equals entered EPI and adds a displayed 10 percent path allowance; width finishing change is not modeled." },
    { q: "How does reed substitution work?", a: "For supported 6-, 8-, 10-, 12-, 15-, 16-, and 20-dent reeds, the tool reduces a whole-number EPI and reed-dent pair to one exact repeating arithmetic sequence. Exact arithmetic does not prove that the yarn fits the reed or that the resulting cloth is suitable." },
    { q: "Does the worksheet predict finished size?", a: "No. It applies only the dimensions and allowances you enter and does not model width change. Confirm take-up, beat, PPI, finishing, and both finished dimensions with a representative woven sample." },
    { q: "Does the calculator infer sett or shrinkage from fiber type?", a: "No. Fiber name alone does not determine either value. Yarn construction, twist, draft, beat, loom setup, and finishing matter, so the tool requires a measured or selected WPI assumption and an explicit user-entered length allowance." },
  ],
  "project-cost-calculator": [
    { q: "What does the project-cost total include?", a: "It adds each entered skein quantity multiplied by its entered price per skein, plus the notion or extra amounts you enter. It is a material subtotal, not a complete budget and not materials plus labor." },
    { q: "Can the calculator compare making with buying?", a: "No. It does not retrieve retail prices or decide whether making or buying is cheaper. You can compare the entered material subtotal with your own separately verified alternative." },
    { q: "How is the time estimate calculated?", a: "Estimated hours equal the entered total stitches divided by the entered stitches per minute and then by 60. It assumes one constant rate and does not include setup, finishing, corrections, or breaks unless you account for them separately." },
    { q: "Does the calculator recommend a selling price?", a: "No. You enter the selling-price scenario yourself. The calculator subtracts entered materials and, when estimated hours are available, divides that remainder by the hours; it does not add labor cost or determine a fair price." },
    { q: "What can I enter as a notion or extra?", a: "You can manually label and enter one-time amounts such as buttons, zippers, stuffing, a pattern, packaging, shipping, taxes, or fees. The calculator cannot know which costs apply and includes only the amounts you add." },
    { q: "How should I choose stitches per minute?", a: "Measure your own rate over a representative section of the intended stitch pattern and enter that assumption. Speed varies within a project, so treat the result as a simple estimate rather than a benchmark or recorded labor time." },
  ],
  "color-pooling-calculator": [
    { q: "What does this color pooling tool show?", a: "It repeats measured whole-stitch color sections across a bounded trial width and displays their idealized placement over several rows. It does not guarantee argyle, plaid, or another fabric result." },
    { q: "How do I measure color sections?", a: "Work the intended stitch and count the whole stitches covered by each color through several repeats when possible. Record variation and enter representative section counts in yarn order." },
    { q: "Does the tool choose the best stitch?", a: "No. Stitch construction, setup, tool size, and tension affect color consumption. Measure and swatch the exact combination you intend to use." },
    { q: "Why can the physical swatch differ from the grid?", a: "Real boundaries can fall within stitches, repeats can vary, and foundations, turns, joins, edges, or tension changes can consume yarn the idealized grid does not model." },
    { q: "What is the difference between turned and same-direction rows?", a: "Turned mode places return rows from right to left while consuming the yarn sequence continuously. Same-direction mode starts every displayed row on the left." },
    { q: "Does the trial row width include foundation or turning chains?", a: "No. It is a worked-stitch count only. Add and verify setup or turning chains from the instructions for the stitch you actually use." },
  ],
  "thread-converter": [
    { q: "What does the thread converter look up?", a: "It searches only the rows included in this site\u2019s DMC, Anchor, and Cosmo reference table. An exact code lookup returns the corresponding values stored on that same row; it does not calculate a nearest color." },
    { q: "Are cross-brand rows guaranteed physical color matches?", a: "No. A shared table row is a reference entry, not proof that the actual threads are visually or spectrally identical. Compare real skeins under the lighting that matters before substituting a critical color." },
    { q: "Does the converter support Sulky or specialty threads?", a: "No. The included lookup covers only the listed DMC, Anchor, and Cosmo fields and does not claim support for Sulky, metallic, variegated, perle-cotton, or machine-embroidery systems." },
    { q: "Can I look up a project list?", a: "Yes. Choose one source-brand field and enter a bounded list of exact codes separated by spaces, commas, semicolons, or new lines. Unknown and ambiguous entries remain visibly unresolved rather than being guessed." },
    { q: "What does exact batch lookup do?", a: "It checks each bounded source-brand code against the included table and preserves found, unknown, invalid, or ambiguous status. It does not choose a substitute or create a verified shopping list." },
    { q: "What is the saved reference palette?", a: "Choose Add on an included row to keep that row in a temporary browser-session reference list. Copying or printing the list does not verify the cross-brand colors, availability, or purchase requirements." },
  ],
  "stitch-pattern-calculator": [
    { q: "What is a stitch multiple?", a: "It is the number of pattern stitches in one repeat. Enter the multiple exactly as stated by the source instruction and verify any separate plus value." },
    { q: "What does multiple of 4 plus 1 mean?", a: "The modeled pattern count equals 4 times a positive whole repeat count plus 1, so 5, 9, 13, and 17 satisfy the arithmetic. The tool does not infer what that plus stitch does in the pattern." },
    { q: "What does the displayed combined spacing mean?", a: "It is the arithmetic distance between simultaneous solutions after compatible constraints are combined. It is not proof that the patterns can be used together." },
    { q: "Can arithmetic compatibility validate a sampler blanket?", a: "No. It checks entered stitch totals only. Row repeats, edges, gauge, construction, shaping, and the source pattern still need separate review." },
    { q: "What if no count works?", a: "The offsets may conflict, or no compatible total may fall inside the selected range after both edge allowances. The tool reports those cases rather than inventing a nearby result." },
    { q: "Does the calculator determine row repeats?", a: "The stitch solver does not infer vertical repeats. The separate Row Planner only rounds the repeat count and target rows that you enter; follow the source for the actual repeat and finishing." },
    { q: "How are edge stitches handled?", a: "The edge field is per side, so the returned total adds it twice. Repeat constraints are checked against the remaining pattern stitches." },
    { q: "What does gauge mode do?", a: "It converts the entered width interval into whole stitch counts using measured stitches per inch. Zero tolerance remains exact and can yield no whole count." },
    { q: "What limits protect the browser?", a: "The tool bounds patterns, multiples, plus values, total stitches, combined spacing, and displayed matches before producing a result list." },
  ],
  "stitch-quick-reference": [
    { q: "How many yarn overs are in a double crochet?", a: "A double crochet uses 4 total yarn overs: 1 before inserting the hook, 1 when pulling up the loop, and 2 more during the two pull-through-2 steps. The initial YO before inserting is what gives DC its height." },
    { q: "What is the turning chain for each crochet stitch?", a: "SC = 1 chain, HDC = 2 chains, DC = 3 chains, TR = 4 chains, DTR = 5 chains. The turning chain number matches the stitch height." },
    { q: "What is the difference between front post and regular double crochet?", a: "The only difference is where you insert the hook. Regular DC goes into the top loops. Front post DC (FPdc) goes around the vertical post of the stitch below. The yarn overs and pull-throughs are identical." },
    { q: "Why does HDC feel different from other stitches?", a: "HDC is the one exception to the crochet pattern. Instead of pulling through 2 loops repeatedly, you pull through all 3 loops at once. This gives it a distinctive third horizontal bar at the top." },
    { q: "What is the difference between SSK and K2tog?", a: "Both reduce 2 stitches to 1. K2tog leans right, insert through 2 stitches and knit. SSK leans left, slip 2 knitwise, then knit together through back loops. Use them as mirrors for symmetrical shaping." },
    { q: "How do I count loops on my hook to check for mistakes?", a: "After pulling up a loop: SC has 2 loops, HDC has 3, DC has 3, TR has 4. Each pull-through-2 step removes one loop. If your count is wrong, you missed a yarn over or pulled through too many." },
  ],
  "uk-to-us-converter": [
    { q: "What is the difference between UK and US crochet terms?", a: "Some common stitch names refer to different stitch heights. For example, UK double crochet maps to US single crochet and UK treble crochet maps to US double crochet. Verify the terminology convention stated by the pattern." },
    { q: "Does this converter work with abbreviations?", a: "It replaces the full terms and abbreviations in its displayed map. Unsupported or ambiguous tokens remain unchanged." },
    { q: "Can I convert US terms to UK terms?", a: "Yes. The US-to-UK direction applies a canonical reverse mapping in one pass. Because multiple source terms can map to one target term, review the result against the pattern's abbreviation key." },
    { q: "Does it handle every vintage or old-fashioned term?", a: "No. A small listed set of legacy phrases is included, but the tool does not identify or resolve every historical usage." },
    { q: "Is this a complete pattern translation?", a: "No. It only replaces mapped terms. It does not validate stitch counts, charts, gauge, construction, or the source convention." },
  ],
  "circle-calculator": [
    { q: "What do the 6, 8, 12, and 16 options mean?", a: "They are common starting-count presets used by this arithmetic reference. They are not universal flatness rules for every yarn, hook, stitch, tension, or join." },
    { q: "Does the schedule guarantee a flat or round circle?", a: "No. It preserves the selected count progression only. Check each round against the selected pattern and the actual fabric, then adjust deliberately if it cups or ripples." },
    { q: "Does the planner calculate diameter or accept gauge?", a: "No. It accepts only a preset and a round limit. It does not predict finished diameter, project size, fit, or yarn use." },
    { q: "Does it choose a magic ring, join, or turning-chain convention?", a: "No. Use the center start and round convention required by the selected pattern, including whether chains count as stitches." },
  ],
  "needle-guide": [
    { q: "What needle should I use to weave in crochet ends?", a: "A tapestry needle (also called a yarn needle). The blunt tip slides between stitches without splitting your yarn." },
    { q: "What is the difference between a tapestry needle and a chenille needle?", a: "Both have large eyes, but a tapestry needle has a blunt tip while a chenille needle is sharp. Use tapestry for yarn work, chenille for piercing tightly woven fabric." },
    { q: "Can I use a regular sewing needle for crochet?", a: "You can in a pinch, but the small eye makes threading yarn difficult and the sharp tip will split your stitches. A tapestry needle is much easier." },
    { q: "What needle do I need to add beads to my crochet?", a: "A beading needle. They are thin enough to fit through seed bead holes. Pre-string your beads onto the yarn before you start crocheting." },
    { q: "What size tapestry needle should I use for different yarn weights?", a: "Match needle eye size to your yarn thickness. For lace and fingering weight, use a size 18–20 tapestry needle. For DK and worsted, a size 14–16 works well. For bulky and super bulky yarn, use a size 13 or larger. The needle should thread easily without bending the yarn." },
  ],
  "cast-on-calculator": [
    { q: "How many stitches do I cast on for a specific width?", a: "Divide your gauge stitches by the gauge measurement to get stitches per inch, then multiply by your desired width. For example, 18 stitches over 4 inches = 4.5 stitches per inch. For a 50-inch blanket, that\u2019s 225 stitches." },
    { q: "What is a stitch pattern multiple?", a: "Many stitch patterns repeat over a fixed number of stitches. If your pattern repeats every 6 stitches, your cast-on count must be a multiple of 6. Our calculator rounds UP to the nearest multiple so your pattern fits evenly." },
    { q: "Do I need to add edge stitches?", a: "If you\u2019re knitting flat pieces that will be seamed, most knitters add 1\u20132 selvedge stitches per side. These stitches get absorbed into the seam and don\u2019t affect the finished width of your project." },
    { q: "How do I figure out my gauge?", a: "Knit a swatch at least 6 inches wide. Lay it flat, measure 4 inches across the center (avoiding edges), and count the stitches. That\u2019s your gauge over 4 inches." },
    { q: "Why does my finished width not match?", a: "Gauge can shift between a small swatch and a large project, especially on circular needles vs flat. Blocking also changes dimensions. Always measure as you go and adjust if needed." },
  ],
  "hat-calculator": [
    { q: "How do I choose a head measurement for this reference?", a: "Measure the intended wearer when possible. The preset ranges are broad orientation only and do not establish a custom fit." },
    { q: "What is negative ease in this calculator?", a: "It is an explicit starting assumption that makes the calculated target circumference smaller than the entered head measurement. The displayed 10%, 15%, and 5% presets are not measured stretch values or fit guarantees." },
    { q: "Why round the cast-on to a multiple of eight?", a: "This specific bottom-up knitted reference divides the crown into eight sections and removes one stitch per section on every decrease round. Another construction may require a different multiple." },
    { q: "How long should I work before the crown decreases?", a: "Use a tested pattern or construction-specific measurement. The displayed height ranges are nominal references; desired coverage, crown depth, gauge, and finishing affect the required length." },
    { q: "How much yarn does the hat calculator estimate?", a: "It does not estimate yarn. Use a pattern-specific quantity or a representative measured method that includes the actual construction." },
    { q: "Can I use the crown schedule for crochet or top-down hats?", a: "Not directly. The schedule models bottom-up knitting with K2tog decreases and plain rounds. Crochet and top-down constructions need their own verified instructions." },
  ],
  "amigurumi-shapes": [
    { q: "What does the sphere option generate?", a: "It generates a bounded six-stitch increase/even/decrease count schedule ending at six stitches. It is an arithmetic reference, not a complete tested pattern or a guarantee of a spherical finished object." },
    { q: "Does the tool choose yarn, hook, gauge, stuffing, or finishing?", a: "No. Those material and construction choices affect size, firmness, gaps, safety, and shape and must be selected and tested for the actual project." },
    { q: "Does the output require joined rounds or a continuous spiral?", a: "The count schedule does not settle that technique choice. Keep the chosen method consistent, mark round boundaries, and verify that the written placement works with it." },
    { q: "How do the other shape options work?", a: "The cone adds six stitches on alternating rounds, the cylinder builds a six-increase circular base then works even, and the oval gives a count-consistent start around a foundation chain. Swatch and adapt each reference before using it in a finished design." },
    { q: "What is sc2tog?", a: "Single crochet two together, a decrease. Insert hook in next stitch, pull up a loop, insert in following stitch, pull up a loop, yarn over and pull through all 3 loops." },
    { q: "Does the tool tell me how to stuff, close, or finish the shape?", a: "No. Stuffing, closing, joining, and tail security depend on the yarn, construction, intended use, and any applicable safety requirements. Follow a tested, project-specific pattern or finishing method." },
  ],
  "amigurumi-pattern-checker": [
    { q: "How do I check the stitch count in an amigurumi round?", a: "Enter the number of stitches available before the round, then paste the round instruction. The checker calculates how many stitches the instruction consumes and creates and compares that result with the written total." },
    { q: "Can this checker find errors in AI-generated crochet patterns?", a: "It can find arithmetic errors in supported round notation, whether a person or AI wrote the pattern. It cannot verify gauge, shaping quality, assembly, safety, or unsupported special stitches, so a real crochet test is still required." },
    { q: "Does FiberTools upload or save my crochet pattern?", a: "No. The checker processes pasted text locally in your browser. It does not send the pattern to a server, save it to an account, publish it, or use it for model training." },
    { q: "What crochet notation does the checker support?", a: "The first release supports US sc, hdc, dc, increases, decreases, sc2tog, hdc2tog, dc2tog, chains, joining slip stitches, FLO, BLO, magic rings, numbered repeats, and simple around instructions." },
    { q: "Why do I need to enter a starting stitch count?", a: "A middle round can only be checked if the tool knows how many stitches are available from the previous round. You can leave the field blank when the first pasted line starts in a magic ring." },
    { q: "Does a correct stitch total prove the whole pattern works?", a: "No. Correct means only that the supported arithmetic is internally consistent. The intended shape, size, gauge, clarity, assembly, and safety still need human review and a physical test." },
  ],
  "wpi-calculator": [
    { q: "What is WPI (wraps per inch)?", a: "WPI stands for Wraps Per Inch. You wrap yarn around a ruler for exactly one inch and count the number of wraps. It\u2019s the most reliable way to identify the weight of unlabeled yarn." },
    { q: "How do I measure WPI accurately?", a: "Wrap your yarn snugly around a ruler or dowel for one inch. Don\u2019t stretch the yarn or leave gaps, and don\u2019t overlap strands. Count the number of wraps. Repeat in 2\u20133 spots and average the results." },
    { q: "Why does my WPI fall between two yarn weights?", a: "WPI ranges overlap between adjacent weights. A yarn at 12 WPI could be Fine/Sport or Medium/Worsted. The best way to confirm is to knit or crochet a gauge swatch and compare your stitch count to the standard ranges." },
    { q: "Can I use WPI for textured or novelty yarn?", a: "Textured yarns like boucl\u00E9, chenille, or eyelash yarn don\u2019t wrap evenly, so WPI measurements are less reliable. For these yarns, swatching is the best way to determine the effective weight." },
    { q: "What tools do I need to measure WPI?", a: "A standard ruler works fine. You can also use a dedicated WPI tool (a notched card or gauge), a pencil, or a dowel. Any straight, smooth surface about \u00BC inch in diameter works." },
    { q: "How does WPI relate to the CYC yarn weight system?", a: "The Craft Yarn Council\u2019s 0\u20137 weight categories correspond to WPI ranges. For example, worsted (CYC 4) is typically 9\u201312 WPI. Our converter maps your WPI to the matching CYC category with needle, hook, and gauge recommendations." },
  ],
  "c2c-calculator": [
    { q: "What is C2C crochet?", a: "C2C (corner-to-corner) is a crochet technique where you build a blanket diagonally. You start with one block in a corner, increase one block per row until you reach the widest diagonal, then decrease back down to the opposite corner." },
    { q: "How do I measure a C2C gauge swatch?", a: "Make and finish a representative multi-block swatch, then record whole block counts and total dimensions on both axes. The planner derives block width and height separately." },
    { q: "What is a diagonal row in C2C?", a: "Each diagonal row runs from one edge of the blanket to the other at a 45-degree angle. The total number of diagonal rows equals blocks wide + blocks tall \u2013 1. This tells you how many rows you\u2019ll work from start to finish." },
    { q: "How does the optional C2C yarn total work?", a: "Enter inches of yarn measured per representative block and an explicit allowance percentage. The calculator scales that input across the nominal total blocks and shows the measured-input base separately from the allowance." },
    { q: "Can I make a rectangular C2C blanket?", a: "Yes. C2C works for any rectangle. You increase diagonally until you reach the shorter side\u2019s block count, then work even rows (increasing one end, decreasing the other) until you reach the longer side, then decrease to the final corner." },
    { q: "Does the C2C plan include a border?", a: "No. Border dimensions, construction, and yarn are separate. Use the selected pattern and a representative sample to plan them." },
  ],
  "sock-calculator": [
    { q: "What does this sock calculator calculate?", a: "It calculates one circular stitch-count checkpoint from the foot circumference, negative-ease assumption, measured stitch gauge, gauge span, and required multiple that you enter." },
    { q: "Does it calculate a heel, gusset, toe, or foot length?", a: "No. It does not infer construction, shaping, length, pull-on fit, or a complete sock pattern. Use a tested sock pattern for those decisions." },
    { q: "Does the default 10% negative ease guarantee fit?", a: "No. Ten percent is an editable starting assumption, not a universal rule. Use the ease required by your pattern and compare the modeled circumference with a representative finished swatch." },
    { q: "How does multiple rounding work?", a: "The adjusted count is rounded to the nearest whole multiple you enter; an exact halfway case rounds upward. The displayed modeled circumference and effective ease show the effect of that rounding." },
    { q: "Why might a half-round checkpoint be missing?", a: "It is displayed only when the rounded total divides evenly into two whole-stitch halves. That arithmetic checkpoint is not a construction instruction." },
  ],
  "granny-square-planner": [
    { q: "How many granny squares do I need for a 50 by 60 inch target?", a: "With measured 6-inch squares, the meet-or-exceed grid is 9 across by 10 tall, or 90 squares. Its nominal span is 54 by 60 inches before joining effects. Use your measured square size for other grids." },
    { q: "How does the planner estimate yarn for the squares?", a: "Enter yarn length measured from one representative square. The planner multiplies that value by total square count. It does not add a hidden allowance or estimate joining, borders, tails, or rejected squares." },
    { q: "Does seam length tell me how much joining yarn to buy?", a: "No. The planner counts every unique internal square edge once and reports that seam distance. Measure your chosen joining method on sample squares before converting distance into a yarn quantity." },
    { q: "What is the best size for granny squares?", a: "There is no universal best size. Compare measured samples for the intended pattern, yarn, hook, handling, layout, and amount of joining." },
    { q: "How do I make sure all my granny squares are the same size?", a: "Use the same yarn, hook, stitch count, and tension, then measure each square. If the pattern and care instructions call for finishing before joining, test that treatment on a representative square and apply it consistently without forcing a target size." },
    { q: "Can I mix different granny square patterns in one blanket?", a: "Yes, but compare measured edge lengths and test the intended joins before assembly. Different stitch patterns can respond differently even when their nominal sizes or round counts match." },
  ],
  "sleeve-calculator": [
    { q: "How does the calculator determine sleeve decreases?", a: "It multiplies each entered circumference by stitch gauge and rounds each result to the nearest whole stitch. For an even difference, dividing by 2 gives the number of modeled paired-decrease events. The tool then partitions its available shaping rows into N-row and, when needed, N+1-row intervals." },
    { q: "What does 'decrease 1 st each end' mean here?", a: "In this model, one event removes two stitches: one at each edge. The selected pattern must define the stitch, placement, lean or direction, side or round, edge treatment, and row-count convention; the calculator does not prescribe a universal technique." },
    { q: "Why does the calculator subtract one inch at each end?", a: "The two fixed one-inch exclusions are assumptions in this calculator's shaping-zone arithmetic. They are not universal buffer requirements. Use the output only if those exclusions match the length landmarks and construction in the selected pattern." },
    { q: "Can I use this for set-in sleeves?", a: "Not as a complete set-in-sleeve calculation. This tool models only a straight paired-decrease taper and does not calculate a sleeve cap, armhole, pickups, compound shaping, construction, ease, or fit." },
    { q: "What if the interval division has a remainder?", a: "For supported inputs, the calculator assigns some events an N-row interval and the rest an N+1-row interval so the displayed intervals total the modeled shaping rows. Confirm the first event, interval order, and row-count convention with the selected pattern." },
    { q: "When will the calculator refuse a sleeve schedule?", a: "It returns an unsupported result when the rounded stitch counts differ by an odd number, because paired events cannot reach the displayed target exactly, or when the model needs more decrease events than available shaping rows. It does not silently change the target or generate a zero-row interval." },
  ],
  "raglan-calculator": [
    { q: "What does this raglan checkpoint calculate?", a: "It converts an entered finished-body circumference and measured stitch gauge into one whole body count rounded to the required multiple you enter." },
    { q: "Does it calculate the neck cast-on or section distribution?", a: "No. The available inputs cannot determine a neckline, front/back/sleeve allocation, raglan-line setup, or underarm split." },
    { q: "Does it produce an increase or yoke schedule?", a: "No. It does not use row gauge, yoke depth, construction, or shaping inputs and therefore cannot calculate increase placement or yoke fit." },
    { q: "What does modeled body circumference mean?", a: "It is the rounded body stitch count divided by the entered stitches per inch. Compare it with the requested finished circumference before using the checkpoint." },
    { q: "Can the result guarantee garment fit?", a: "No. Use a tested raglan pattern, intended ease, body measurements, and a representative blocked swatch for construction and fit decisions." },
  ],
  "blocking-calculator": [
    { q: "What does the blocking calculator calculate?", a: "It calculates the signed percentage change from a current measurement to a requested measurement. Positive means an increase, negative means a decrease, and width and length are calculated independently." },
    { q: "Does the percentage predict what blocking will achieve?", a: "No. It describes the requested change only. Yarn construction, blend, dye, stitch pattern, prior treatment, finishing method, and drying conditions can all affect the outcome." },
    { q: "How do I choose a finishing method?", a: "Follow the pattern and the yarn, fabric, or garment care instructions. Test the intended treatment on a representative swatch and measure it after the complete treatment and drying cycle." },
    { q: "Can the calculator tell me whether a size change is safe?", a: "No. It does not assign feasibility or safety ratings. Use the swatch result and product-specific instructions; get qualified textile-care guidance when instructions conflict or the item is valuable." },
    { q: "Can I use steam or another heat treatment?", a: "Only when the product and appliance instructions permit it. Heat can irreversibly alter some fibers, finishes, dyes, and constructions, so a generic fiber name is not enough to establish a safe treatment." },
  ],
  "stash-estimator": [
    { q: "How do I weigh a partial skein?", a: "Use a kitchen scale that measures in grams. Place the partial skein on the scale. If the yarn is on a project, weigh the project and subtract the estimated weight of your work, or wind off the remaining yarn and weigh it separately." },
    { q: "How accurate is the partial skein estimate?", a: "It is quite accurate for commercial machine-spun yarn with consistent thickness. Handspun or art yarns with thick-and-thin sections may vary. The estimate is based on the proportion of weight remaining compared to a full skein." },
    { q: "What if I do not have the original ball band?", a: "Use the yardage reference table. Identify the yarn weight by WPI or visual comparison, then use the typical yardage per 100g value for that weight category. Our WPI Calculator can help identify the weight." },
    { q: "Why does fiber content affect the estimate?", a: "Different fibers have different densities. Cotton is heavier per yard than wool, so a 50g ball of cotton has fewer yards than a 50g ball of wool at the same thickness. The weight-based formula assumes the same fiber as the original skein." },
    { q: "Can I use this for cakes and hanks?", a: "Yes. The formula works for any yarn put-up, skeins, balls, cakes, or hanks. You need the full weight and yardage from the label, plus the current weight of your partial amount." },
    { q: "How do I identify unlabeled yarn weight?", a: "Measure wraps per inch by wrapping yarn snugly around a ruler. 14+ WPI is fingering, 11–12 is DK, 9–10 is worsted, 6–8 is bulky. Our WPI Calculator gives a detailed breakdown with needle and hook recommendations." },
  ],
  "vintage-pattern-decoder": [
    { q: "Does every vintage crochet pattern use UK terms?", a: "No. A pattern's age or appearance does not establish its terminology convention. Check the pattern key, publisher information, or another reliable source. Leave the tool on Unknown when the convention is not established." },
    { q: "What does 'dc' mean in a pattern?", a: "It depends on the established source convention. UK double crochet corresponds to US single crochet, while US dc means US double crochet. Unknown and US modes preserve the text; the tool maps dc only when you explicitly select UK." },
    { q: "What does 'tension' mean in a pattern?", a: "Tension is commonly used where US instructions may say gauge. The word can be a useful research clue, but it does not by itself prove a pattern's country, date, or complete terminology convention." },
    { q: "What does 'wl fwd' mean in a knitting pattern?", a: "It commonly indicates moving the working yarn forward. Whether that movement forms a yarn over depends on the surrounding instruction, so verify the pattern's abbreviation key and next stitch." },
    { q: "How do I tell whether a pattern uses UK or US crochet terms?", a: "Start with the pattern's own abbreviation key and publisher information. Compare multiple defined stitches if possible. Words such as tension or gauge can be clues, but no single clue shown by this tool establishes the convention." },
    { q: "Does the tool date or identify the origin of a pattern?", a: "No. It reports a limited set of possible wording, size, and yarn-weight signals for manual research. Those signals do not establish a publication date or country." },
    { q: "What is 'cast off' in a pattern?", a: "Cast off is commonly called bind off in US knitting instructions. The tool maps the phrase only in explicit UK mode; check the source key before relying on the substitution." },
  ],
  "fabric-substitute": [
    { q: "What is the best way to choose a fabric substitute?", a: "Match construction first, then compare stretch, weight, drape, structure, opacity, and recovery. A woven-to-woven or knit-to-knit substitution with overlapping ranges is safer, but a washed test swatch is still the final check." },
    { q: "Can I replace a woven fabric with a knit?", a: "Usually not without changing the pattern. Knits stretch and recover differently, while woven patterns may rely on darts, closures, or wearing ease. The finder heavily penalizes woven-to-knit matches and labels them poor when the behavior conflicts." },
    { q: "Does the fabric score guarantee the project will work?", a: "No. The score is a transparent comparison of seven broad fabric properties, not a guarantee. Mill finish, fiber blend, washing, pattern ease, and the exact fabric in your hand can change the result." },
    { q: "What does GSM mean for fabric?", a: "GSM means grams per square meter, a measure of fabric mass per area. It helps compare weight, but two fabrics with the same GSM can still have very different thickness, drape, stretch, or warmth." },
    { q: "Why are the fabric ranges broad?", a: "Names such as satin, linen, crepe, fleece, and twill describe families rather than one fixed specification. Fiber, yarn size, weave or knit settings, and finishing vary by mill, so the tool uses documented working ranges and tells you to verify the actual fabric." },
  ],
};
