export interface FAQ {
  q: string;
  a: string;
}

export const toolFaqs: Record<string, FAQ[]> = {
  "yarn-calculator": [
    { q: "How do I calculate how much yarn I need?", a: "Enter your project type, size, yarn weight, and stitch pattern into our calculator. It uses industry-standard yardage estimates adjusted for your specific combination to give you an accurate total with a 10% safety buffer." },
    { q: "How much yarn do I need for a blanket?", a: "A throw blanket (50\u00D760\") typically needs 1,200\u20132,000 yards of worsted weight yarn. The exact amount depends on your stitch pattern, gauge, and yarn weight. Use our calculator for a precise estimate." },
    { q: "How many skeins of yarn do I need for a sweater?", a: "An adult sweater typically needs 1,000\u20131,800 yards depending on size and yarn weight. That\u2019s roughly 5\u20138 skeins of worsted weight yarn. Enter your specific measurements for an exact count." },
    { q: "Does stitch pattern affect yarn usage?", a: "Yes, significantly. Cable patterns use 20\u201330% more yarn than stockinette. Lace patterns use less. Brioche uses about 50% more. Our calculator adjusts for 17 different stitch patterns." },
    { q: "Should I buy extra yarn?", a: "Always. Our calculator includes a 10% buffer, but we recommend buying one extra skein from the same dye lot. Yarn from different dye lots can have subtle color differences." },
    { q: "What is yarn weight?", a: "Yarn weight refers to the thickness of the yarn strand, rated 0 (lace) through 7 (jumbo). Worsted weight (4) is the most common. Thicker yarn covers more area per yard but creates a bulkier fabric." },
  ],
  "needle-converter": [
    { q: "What size knitting needles should I use?", a: "Check your yarn label for the recommended needle size. Our converter shows the equivalent size across US, metric (mm), UK, and Japanese systems so you can match any pattern regardless of origin." },
    { q: "How do I convert US needle sizes to mm?", a: "US sizes don\u2019t follow a linear scale. For example, US 6 = 4.0mm, US 7 = 4.5mm, US 8 = 5.0mm. Our converter handles all 23 sizes from US 0 (2.0mm) to US 50 (25.0mm)." },
    { q: "What size crochet hook do I need?", a: "It depends on your yarn weight. Lace yarn uses 1.5\u20132.25mm hooks, worsted uses 5.0\u20136.0mm hooks, and bulky uses 6.5\u20139.0mm hooks. Our chart shows recommendations for every weight." },
    { q: "Are UK and US needle sizes the same?", a: "No. UK sizes run backwards \u2014 a UK 14 is 2.0mm (tiny) while a US 14 is 10.0mm (large). Our converter prevents this common confusion by showing all systems side by side." },
    { q: "What\u2019s the difference between US and metric crochet hooks?", a: "US crochet hooks use letter sizes (B through S) while metric uses millimeters. For example, US H/8 = 5.0mm. Our converter maps all 24 common hook sizes across both systems." },
    { q: "Can I substitute a different needle size?", a: "Yes, but it will change your gauge. Going up a size creates a looser, drapier fabric. Going down creates a tighter, firmer fabric. Always swatch first when substituting." },
  ],
  "gauge-calculator": [
    { q: "What is gauge in knitting and crochet?", a: "Gauge is the number of stitches and rows per unit of measurement (usually 4 inches or 10cm). It determines the finished size of your project. Even a half-stitch difference per inch can change a sweater by a full size." },
    { q: "How do I measure my gauge?", a: "Knit or crochet a swatch at least 6 inches square. Lay it flat without stretching. Measure the number of stitches across 4 inches and rows down 4 inches in the center of the swatch." },
    { q: "Why doesn\u2019t my gauge match the pattern?", a: "Everyone knits and crochets at different tensions. Try going up a needle/hook size if you have too many stitches per inch (tight), or down a size if too few (loose)." },
    { q: "Do I really need to make a gauge swatch?", a: "For anything where size matters (garments, hats, socks), absolutely yes. For blankets and scarves where exact dimensions are flexible, you can skip it but may use more or less yarn than expected." },
    { q: "How do I resize a pattern to my gauge?", a: "Use our Resize Pattern tab. Enter the pattern\u2019s gauge and your gauge, and we\u2019ll recalculate every stitch and row count, including stitch multiple rounding." },
    { q: "What is a stitch multiple?", a: "Many stitch patterns repeat over a fixed number of stitches (e.g., a cable that repeats every 8 stitches). Your total stitch count must be divisible by this number, plus any edge stitches. Our calculator handles this rounding." },
  ],
  "yarn-weight-chart": [
    { q: "What are the yarn weight categories?", a: "The Craft Yarn Council defines 8 categories: 0 (Lace), 1 (Fingering/Sock), 2 (Sport), 3 (DK), 4 (Worsted/Aran), 5 (Bulky), 6 (Super Bulky), and 7 (Jumbo). Each has specific gauge and needle size ranges." },
    { q: "What is DK weight yarn?", a: "DK (Double Knitting) is weight category 3. It\u2019s lighter than worsted, typically knits at 5.5\u20136 stitches per inch on US 5\u20137 needles. In the UK it\u2019s called DK, in Australia it\u2019s 8-ply." },
    { q: "Can I substitute DK for worsted weight?", a: "They\u2019re close but not identical. DK is thinner and will give a drapier, lighter fabric. You\u2019ll need more yardage and should adjust your needle size. Our substitution checker shows compatibility scores." },
    { q: "What does ply mean in yarn?", a: "Ply originally meant the number of strands twisted together, but it\u2019s evolved into a weight system in Australia and the UK. An 8-ply yarn is roughly DK weight, 10-ply is worsted, regardless of actual strand count." },
    { q: "What\u2019s the difference between UK and US yarn terms?", a: "US \u2018worsted\u2019 is UK \u2018aran.\u2019 US \u2018fingering\u2019 is UK \u20184-ply.\u2019 US \u2018DK\u2019 is the same in both. Our chart shows US, UK, and Australian terms side by side to prevent confusion." },
    { q: "How do I find the weight of unlabeled yarn?", a: "Wrap the yarn around a ruler for one inch without stretching. Count the wraps: 14\u201318 wraps = fingering, 10\u201312 = DK, 8\u201310 = worsted, 5\u20138 = bulky." },
  ],
  "stitch-counter": [
    { q: "How do I count stitches while knitting?", a: "Use our digital stitch counter. Tap the + button after each row or repeat. The large display is designed for one-handed use while your other hand holds your work." },
    { q: "Can I track multiple counters at once?", a: "Yes, you can run up to 6 independent counters simultaneously. Name each one (e.g., \u2018rows,\u2019 \u2018pattern repeats,\u2019 \u2018decreases\u2019) and track them all on one screen." },
    { q: "Will my count save if I close the browser?", a: "Yes. Your counters automatically save to your browser\u2019s local storage. They\u2019ll be right where you left them when you come back, even after closing the tab." },
    { q: "What are row reminders?", a: "Set a reminder at any row number with a note (e.g., \u2018Row 12: start decreases\u2019). When your counter reaches that row, a popup will alert you so you don\u2019t miss shaping instructions." },
    { q: "Is there an undo button?", a: "Yes. Every tap is tracked with a 50-action undo/redo history. If you accidentally tap +, just hit undo to go back." },
    { q: "Can I use this on my phone?", a: "Absolutely. The counter is designed for mobile with extra-large tap targets, one-thumb operation, and a fullscreen mode that hides browser chrome for distraction-free counting." },
  ],
  "blanket-calculator": [
    { q: "How big should a throw blanket be?", a: "A standard throw blanket is 50\u00D760 inches (127\u00D7152cm). It\u2019s the most popular size for sofa blankets. Our calculator includes 12 standard sizes from lovey (12\u00D712\") to California king (104\u00D7104\")." },
    { q: "How many chains do I need for a throw blanket?", a: "It depends on your yarn weight and gauge. With worsted yarn at 4 stitches per inch, a 50-inch throw needs about 200 chains. Enter your exact gauge into our calculator for a precise number with stitch multiple rounding." },
    { q: "How much yarn do I need for a baby blanket?", a: "A baby/crib blanket (36\u00D752\") typically needs 900\u20131,400 yards of worsted weight yarn, or about 4\u20136 skeins. The exact amount depends on your stitch pattern and gauge." },
    { q: "What is pillow tuck?", a: "Pillow tuck adds extra length (about 20 inches) to the top of a bed blanket so it can fold over the pillows for a finished look. Toggle it on in our calculator for bed-sized blankets." },
    { q: "How do I calculate overhang for a bed blanket?", a: "Overhang is how far the blanket drapes over the sides of the mattress. Typical overhang is 10\u201315 inches. Our calculator adds this to both sides and the foot of the bed automatically." },
    { q: "How many skeins do I need?", a: "Enter your skein yardage (found on the label) and our calculator divides total yardage by skein yardage, rounding up. We include a 10% buffer for swatching and joining." },
  ],
  "increase-decrease-calculator": [
    { q: "How do I increase evenly across a row?", a: "Divide your current stitch count by the number of increases. Our calculator gives you exact stitch-by-stitch instructions like \u2018K7, M1, repeat 11 times\u2019 with balanced distribution of any remainders." },
    { q: "What\u2019s the difference between increasing in a row vs. in the round?", a: "In a flat row, you have edges, so increases are distributed between the first and last stitch. In the round, increases are distributed evenly around the full circumference with no edges to account for." },
    { q: "How do I decrease evenly?", a: "Same principle as increasing. Enter your current count and target count, and we\u2019ll generate instructions using K2tog (knitting) or SC2tog (crochet) spaced evenly across the row." },
    { q: "What does M1 mean?", a: "M1 (Make 1) is a nearly invisible increase. You lift the bar between two stitches and knit into the back of it. M1L leans left, M1R leans right. It\u2019s the cleanest increase method." },
    { q: "What if the number doesn\u2019t divide evenly?", a: "Our calculator handles remainders by distributing them across the row. Some sections will have one extra stitch between increases. The written instructions show exactly where." },
    { q: "Can I get crochet instructions too?", a: "Yes. We generate both knitting and crochet instructions side by side. Knitting uses M1/K2tog terminology, crochet uses \u20182 SC in next st\u2019 and \u2018SC2tog.\u2019" },
  ],
  "stripe-generator": [
    { q: "How do I plan stripes for a blanket?", a: "Add your yarn colors, set the stripe width (fixed or random), and hit generate. Our tool creates a visual preview with per-color row breakdowns so you know exactly how much of each color you\u2019ll use." },
    { q: "What is the weighted randomizer?", a: "Assign a weight to each color to control how often it appears. Give more weight to colors you have extra yarn for (stash busting) and less to accent colors." },
    { q: "How do I avoid two of the same color next to each other?", a: "Our random and fixed modes automatically prevent consecutive same-color stripes. Only the sequence mode (A-B-C-A-B-C) follows a fixed order." },
    { q: "Can I use this for scrap yarn projects?", a: "Absolutely \u2014 that\u2019s what the weighted randomizer is for. Add all your leftover yarn colors, weight them by how much you have, and generate a balanced random pattern." },
    { q: "How many rows should each stripe be?", a: "It\u2019s personal preference. 2\u20134 rows creates a busy pattern, 6\u201310 rows creates bolder stripes. Use random widths (min/max) for a more organic, modern look." },
    { q: "Can I print or save the pattern?", a: "Yes. Use the copy button to get a text list of every stripe, or use the print button for a printable reference. You can also screenshot the visual preview." },
  ],
  "abbreviation-glossary": [
    { q: "What does SSK mean in knitting?", a: "SSK stands for Slip, Slip, Knit. It\u2019s a left-leaning decrease where you slip two stitches knitwise one at a time, then knit them together through the back loops." },
    { q: "What does SC mean in crochet?", a: "SC stands for Single Crochet (US term). In UK patterns, the same stitch is called DC (Double Crochet). This is one of the most common sources of confusion between US and UK patterns." },
    { q: "What\u2019s the difference between US and UK crochet terms?", a: "US and UK crochet terms are offset by one. A US Single Crochet = UK Double Crochet. A US Double Crochet = UK Treble. Our glossary shows both with a UK/US toggle." },
    { q: "What does FLO mean?", a: "FLO stands for Front Loop Only. Instead of working through both loops of a stitch, you insert your hook or needle through only the front loop. This creates a ridged texture." },
    { q: "How do I read a knitting pattern?", a: "Use our Pattern Translator. Paste a line from your pattern and every abbreviation gets highlighted with its full meaning. It\u2019s like a real-time dictionary for pattern instructions." },
    { q: "What does YO mean?", a: "YO stands for Yarn Over. You wrap the yarn around your needle to create a new stitch and a decorative hole. It\u2019s the foundation of lace knitting." },
  ],
  "spinning-ratio-calculator": [
    { q: "How do I calculate my spinning wheel\u2019s drive ratio?", a: "Measure the diameter of your drive wheel and the diameter of the whorl (pulley). Divide the drive wheel diameter by the whorl diameter. For example, a 22-inch wheel with a 2.5-inch whorl = 8.8:1 ratio." },
    { q: "What ratio do I need for sock yarn?", a: "Sock yarn (fingering weight) typically requires a ratio of 8:1 to 14:1 to get enough twist for durability. Higher ratios add more twist per treadle, which is what you want for strong, thin singles." },
    { q: "What is TPI in spinning?", a: "TPI stands for Twists Per Inch. It measures how many times the fiber twists in one inch of yarn. More TPI = stronger, harder yarn. Less TPI = softer, loftier yarn." },
    { q: "How much plying twist do I need?", a: "For balanced 2-ply yarn, ply at roughly 60% of your singles TPI in the opposite direction. Our calculator gives you the exact plying twist based on your singles TPI and number of plies." },
    { q: "What does scotch tension mean?", a: "Scotch tension is a braking system where a band applies friction to the bobbin. The drive band turns the flyer, and the scotch tension controls how fast the yarn winds on. It\u2019s the most common system for beginners." },
    { q: "How do I choose the right whorl?", a: "Smaller whorls = higher ratio = more twist = thinner yarn. Larger whorls = lower ratio = less twist = thicker yarn. Our reference chart matches whorl ratios to target yarn weights." },
  ],
  "cross-stitch-calculator": [
    { q: "How do I calculate the finished size of my cross stitch?", a: "Divide your pattern\u2019s stitch count by the fabric count. For example, a 150\u00D7200 stitch pattern on Aida 14 = 10.7\u00D714.3 inches. Our calculator shows the size on 10 different fabric counts at once." },
    { q: "What is the best Aida count for beginners?", a: "Aida 14 count is the most popular and beginner-friendly. The holes are easy to see, and it works with standard 2-strand floss. Aida 11 is even easier but produces larger finished pieces." },
    { q: "How much floss do I need?", a: "On average, one cross stitch uses about 1.1 inches of floss (with 2 strands). A standard DMC skein (8 meters/8.7 yards) covers roughly 430 full cross stitches. Enter your stitch count per color for an exact estimate." },
    { q: "What does stitching over two mean?", a: "On evenweave or linen fabric, each cross stitch covers 2 fabric threads instead of 1 hole. This halves the effective count: 28-count linen over two = same size as 14-count Aida." },
    { q: "How much extra fabric do I need for framing?", a: "Add at least 3 inches on each side for framing. For scroll frames or hoops, add more. Our calculator adds your chosen margin to the design dimensions automatically." },
    { q: "Can I use this for different fabric types?", a: "Yes. We support Aida (11, 14, 16, 18), Hardanger (22), evenweave (25, 28), and linen (32, 36, 40). The over-two toggle adjusts calculations for evenweave and linen." },
  ],
  "weaving-sett-calculator": [
    { q: "What is sett in weaving?", a: "Sett (also called EPI \u2014 Ends Per Inch) is the number of warp threads per inch in your fabric. The right sett depends on your yarn weight and weave structure. Too open = sleazy fabric. Too tight = stiff and warp-dominant." },
    { q: "How do I calculate sett?", a: "The standard method: wrap your yarn around a ruler for 1 inch, count the wraps (WPI), then multiply by a factor based on your weave structure. Plain weave uses 50% of WPI, twill uses 60%. Our calculator does this automatically." },
    { q: "What is loom waste?", a: "Loom waste is the unusable warp length tied to the loom. It includes the warp tied to front and back beams plus any unusable length. Typical loom waste is 18\u201336 inches depending on your loom." },
    { q: "How do I substitute a different reed?", a: "Use our Reed Substitution tab. Enter your desired EPI and your available reed dent, and we\u2019ll tell you how to thread it (e.g., alternate 1 and 2 threads per dent)." },
    { q: "How much yarn do I need for weaving?", a: "Enter your project dimensions, sett, and loom waste in our Warp Length tab. We calculate total warp and weft yardage including shrinkage allowance for your fiber type." },
    { q: "Does fiber type affect sett?", a: "Yes. Sticky fibers like wool can be sett closer because they grip each other. Slippery fibers like silk or bamboo need a tighter sett (more threads) to prevent shifting." },
  ],
  "project-cost-calculator": [
    { q: "How much does it cost to crochet a blanket?", a: "Material costs typically range from $30\u2013$150 depending on yarn quality, weight, and blanket size. Acrylic worsted for a throw runs about $40\u201360. Premium wool or cotton can be $100\u2013200+." },
    { q: "Is it cheaper to knit or buy?", a: "For simple items like scarves and hats, handmade costs are similar to store-bought. For blankets and sweaters, handmade is usually more expensive in materials alone, before counting your time. The value is in quality, customization, and the joy of making." },
    { q: "How long does it take to crochet a blanket?", a: "A throw blanket takes roughly 30\u201380 hours depending on stitch complexity and your speed. At 25 stitches per minute with worsted yarn, a basic throw takes about 50 hours." },
    { q: "What\u2019s a fair price for handmade items?", a: "A common formula: (materials \u00D7 2) + (hours \u00D7 your desired hourly rate). Our calculator shows your effective hourly rate for any selling price so you can price fairly." },
    { q: "What are notions?", a: "Notions are the non-yarn supplies for your project: buttons, zippers, stitch markers, stuffing, tapestry needles, pattern costs, etc. Add them to our calculator for a complete budget." },
    { q: "How do I estimate stitches per minute?", a: "Beginners average 15\u201320 stitches per minute. Intermediate crafters average 25\u201335. Experienced speed knitters/crocheters can hit 40+. Time yourself over 5 minutes for your personal speed." },
  ],
  "color-pooling-calculator": [
    { q: "What is color pooling?", a: "Color pooling (or planned pooling) is a technique where you use variegated yarn with a specific stitch count to make the colors stack into vertical columns, creating argyle or plaid-like patterns from a single ball of yarn." },
    { q: "How do I measure color sections?", a: "Work a swatch and count exactly how many stitches each color lasts before changing to the next. Enter these counts in order into our calculator. Accuracy here is key to successful pooling." },
    { q: "What stitch works best for color pooling?", a: "Moss stitch (SC, CH1, skip 1) is the most popular because it creates clean, consistent columns. Single crochet and linen stitch also work well." },
    { q: "Why isn\u2019t my pooling lining up?", a: "Usually it\u2019s a gauge issue. Even a slight change in tension shifts the color alignment. Try our adjust buttons (\u00B11 or \u00B12 chains) to fine-tune, or change your hook size." },
    { q: "Does every variegated yarn work for pooling?", a: "Yarn with distinct, consistent color changes works best. Short color changes (2\u20134 stitches each) pool more visibly. Long gradual transitions don\u2019t pool as cleanly." },
    { q: "How do I know how many chains to start with?", a: "Your foundation chain should equal the total number of stitches in one complete color repeat. Our calculator figures this out and shows a live preview of how the colors will stack." },
  ],
  "thread-converter": [
    { q: "How do I convert DMC to Anchor thread numbers?", a: "Type any DMC number into our search box and we\u2019ll instantly show the Anchor and Cosmo equivalents. We currently cover 80 of the most popular colors with more being added." },
    { q: "Are thread conversions exact matches?", a: "Most conversions are close matches, not identical. Different brands use different dye processes, so colors may vary slightly. Always compare threads in person for critical color matching." },
    { q: "What\u2019s the most popular embroidery thread brand?", a: "DMC is the most widely used brand worldwide, with 500 numbered colors. Anchor is popular in the UK and Europe. Cosmo is a Japanese brand known for excellent color saturation." },
    { q: "Can I search by color name?", a: "Yes. Our search works with thread numbers (e.g., \u2018310\u2019) and color names (e.g., \u2018red,\u2019 \u2018forest green\u2019). You can filter by brand to narrow results." },
    { q: "How do I convert a whole shopping list at once?", a: "Use our Bulk Convert tab. Paste a list of DMC numbers separated by commas or spaces, and we\u2019ll convert all of them in one shot with a printable results table." },
    { q: "What is the palette builder?", a: "Click the + button next to any search result to add it to your palette. The palette tab shows all your selected colors with every brand\u2019s number, ready to copy or print as a shopping list." },
  ],
};
