export interface Tool {
  slug: string;
  name: string;
  shortName: string;
  description: string;
  category: ToolCategory;
  icon: string;
  tier: 1 | 2 | 3;
  ready: boolean;
  keywords: string[];
}
export type ToolCategory = 
  | "knitting" 
  | "crochet" 
  | "both" 
  | "weaving" 
  | "spinning" 
  | "embroidery" 
  | "cross-stitch"
  | "sewing";
export const CATEGORY_LABELS: Record<ToolCategory, string> = {
  knitting: "Knitting",
  crochet: "Crochet",
  both: "Knitting & Crochet",
  weaving: "Weaving",
  spinning: "Spinning",
  embroidery: "Embroidery",
  "cross-stitch": "Cross Stitch",
  sewing: "Sewing",
};
export const CATEGORY_COLORS: Record<ToolCategory, string> = {
  knitting: "bg-rose-100 text-rose-700 dark:bg-rose-900/30 dark:text-rose-300",
  crochet: "bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-300",
  both: "bg-sage-100 text-sage-700 dark:bg-sage-900/30 dark:text-sage-300",
  weaving: "bg-bark-100 text-bark-700 dark:bg-bark-700 dark:text-bark-200",
  spinning: "bg-cream-300 text-bark-700 dark:bg-bark-700 dark:text-cream-300",
  embroidery: "bg-rose-100 text-rose-700 dark:bg-rose-900/30 dark:text-rose-300",
  "cross-stitch": "bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-300",
  sewing: "bg-plum-100 text-plum-700 dark:bg-plum-900/30 dark:text-plum-300",
};
export const tools: Tool[] = [
  {
    slug: "yarn-calculator",
    name: "Yarn Yardage Calculator",
    shortName: "Yarn Calculator",
    description: "Scale yarn measured in a representative swatch to a flat rectangular target, then convert the planning total to whole skeins.",
    category: "both",
    icon: "🧶",
    tier: 1,
    ready: true,
    keywords: ["yarn calculator", "how much yarn do I need", "yarn yardage calculator"],
  },
  {
    slug: "needle-converter",
    name: "Needle & Hook Size Converter",
    shortName: "Needle Converter",
    description: "Instantly convert knitting needle and crochet hook sizes between US, UK, metric, and Japanese systems.",
    category: "both",
    icon: "🪡",
    tier: 1,
    ready: true,
    keywords: ["knitting needle size chart", "crochet hook conversion", "needle size converter"],
  },
  {
    slug: "gauge-calculator",
    name: "Gauge Calculator & Pattern Resizer",
    shortName: "Gauge Calculator",
    description: "Calculate measured gauge and proportionally scale entered stitch or row counts; pattern repeats, shaping, and fit still need separate review.",
    category: "both",
    icon: "📐",
    tier: 1,
    ready: true,
    keywords: ["gauge calculator", "pattern resizer", "stitch calculator"],
  },
  {
    slug: "yarn-weight-chart",
    name: "Yarn Weight & Substitution Guide",
    shortName: "Yarn Weights",
    description: "Yarn weight reference with common US, UK, and Australian names, knitting gauge guidelines, and a swatch-first label comparison.",
    category: "both",
    icon: "⚖️",
    tier: 1,
    ready: true,
    keywords: ["yarn weight chart", "yarn substitution", "DK vs worsted"],
  },
  {
    slug: "fabric-substitute",
    name: "Fabric Substitute Finder",
    shortName: "Fabric Substitutes",
    description: "Compare 30 garment fabrics by construction, stretch, weight, drape, structure, opacity, and recovery, or find projects suited to fabric you already own.",
    category: "sewing",
    icon: "🧵",
    tier: 1,
    ready: true,
    keywords: ["fabric substitute", "fabric substitution chart", "what can I make with this fabric", "fabric compatibility"],
  },
  {
    slug: "stitch-counter",
    name: "Stitch & Row Counter",
    shortName: "Stitch Counter",
    description: "Track up to six named counts and set exact-count reminders on the first counter. Browser-local saving is attempted but not guaranteed.",
    category: "both",
    icon: "🔢",
    tier: 1,
    ready: true,
    keywords: ["stitch counter online", "row counter", "knitting counter"],
  },
  {
    slug: "amigurumi-pattern-checker",
    name: "Amigurumi Pattern Checker",
    shortName: "Pattern Checker",
    description: "Check crochet round math line by line. See stitches consumed, stitches created, written totals, and possible errors.",
    category: "crochet",
    icon: "✓",
    tier: 1,
    ready: true,
    keywords: ["crochet pattern checker", "amigurumi stitch count checker", "crochet round calculator"],
  },
  {
    slug: "blanket-calculator",
    name: "Blanket Size Calculator",
    shortName: "Blanket Calculator",
    description: "Calculate blanket stitch counts and estimate yarn from a measured swatch for sizes from baby to king.",
    category: "both",
    icon: "🛏️",
    tier: 2,
    ready: true,
    keywords: ["blanket size chart", "crochet blanket sizes", "blanket calculator"],
  },
  {
    slug: "increase-decrease-calculator",
    name: "Increase & Decrease Calculator",
    shortName: "Inc/Dec Calculator",
    description: "Build a bounded stitch-by-stitch plan for distributing an entered increase or decrease across one row or round.",
    category: "both",
    icon: "↕️",
    tier: 2,
    ready: true,
    keywords: ["increase evenly calculator", "decrease evenly knitting"],
  },
  {
    slug: "stripe-generator",
    name: "Stripe Pattern Generator",
    shortName: "Stripe Generator",
    description: "Generate a bounded random, weighted, or repeating stripe-row sequence from the colors and row limits you enter.",
    category: "both",
    icon: "🌈",
    tier: 2,
    ready: true,
    keywords: ["random stripe generator", "stripe pattern creator"],
  },
  {
    slug: "abbreviation-glossary",
    name: "Abbreviation & Stitch Glossary",
    shortName: "Abbreviations",
    description: "Searchable glossary of knitting and crochet abbreviations with US/UK toggle, stitch descriptions, and step-by-step diagrams.",
    category: "both",
    icon: "📖",
    tier: 2,
    ready: true,
    keywords: ["crochet abbreviations", "knitting abbreviations chart"],
  },
  {
    slug: "spinning-ratio-calculator",
    name: "Spinning Wheel Drive Ratio Calculator",
    shortName: "Spinning Calculator",
    description: "Calculate the ideal geometric ratio between a drive wheel and its connected pulley.",
    category: "spinning",
    icon: "🌀",
    tier: 2,
    ready: true,
    keywords: ["spinning wheel ratio", "drive ratio calculator"],
  },
  {
    slug: "stitch-pattern-calculator",
    name: "Stitch Pattern Calculator",
    shortName: "Stitch Calculator",
    description: "Find bounded stitch counts compatible with the entered pattern multiples and plan a supported sampler layout.",
    category: "both",
    icon: "🧮",
    tier: 2,
    ready: true,
    keywords: ["stitch pattern calculator", "crochet stitch multiple calculator", "sampler blanket planner"],
  },
  {
    slug: "stitch-quick-reference",
    name: "Stitch Quick Reference",
    shortName: "Stitch Reference",
    description: "Visual step-by-step reference for the included common stitches, with yarn overs, pull-throughs, loop counts, and turning-chain notes.",
    category: "both",
    icon: "🃏",
    tier: 2,
    ready: true,
    keywords: ["crochet stitch diagram", "how to double crochet", "stitch quick reference", "crochet stitch steps"],
  },
  {
    slug: "cross-stitch-calculator",
    name: "Cross Stitch Size & Thread Calculator",
    shortName: "Cross Stitch Calc",
    description: "Calculate dimensions for an entered stitch count and supported fabric count, with a planning estimate for stranded-cotton use.",
    category: "cross-stitch",
    icon: "✂️",
    tier: 3,
    ready: true,
    keywords: ["cross stitch size calculator", "aida cloth calculator"],
  },
  {
    slug: "weaving-sett-calculator",
    name: "Weaving Sett Calculator",
    shortName: "Sett Calculator",
    description: "Calculate a starting sett and warp worksheet from entered WPI and show only supported reed-sleying options; sample the cloth before committing.",
    category: "weaving",
    icon: "🏗️",
    tier: 3,
    ready: true,
    keywords: ["weaving sett calculator", "ends per inch calculator"],
  },
  {
    slug: "project-cost-calculator",
    name: "Project Cost Calculator",
    shortName: "Cost Calculator",
    description: "Total the yarn, notions, and extras you enter, with an optional stitch-rate time estimate and selling-price scenario.",
    category: "both",
    icon: "💰",
    tier: 3,
    ready: true,
    keywords: ["crochet cost calculator", "knitting cost calculator"],
  },
  {
    slug: "color-pooling-calculator",
    name: "Planned Pooling Crochet Calculator",
    shortName: "Color Pooling",
    description: "Preview how an entered repeating color-run sequence maps across a chosen stitch count; swatching is still required.",
    category: "both",
    icon: "🎨",
    tier: 3,
    ready: true,
    keywords: ["color pooling calculator", "planned pooling crochet"],
  },
  {
    slug: "thread-converter",
    name: "Embroidery Thread Converter",
    shortName: "Thread Converter",
    description: "Look up exact entries in the included DMC, Anchor, and Cosmo embroidery-thread table.",
    category: "embroidery",
    icon: "🧵",
    tier: 3,
    ready: true,
    keywords: ["DMC to anchor conversion", "embroidery thread converter"],
  },
  {
    slug: "uk-to-us-converter",
    name: "UK to US Crochet Terms Converter",
    shortName: "UK/US Converter",
    description: "Replace supported modern UK and US crochet terms in pasted text using a one-pass mapping; all other text is left unchanged.",
    category: "crochet",
    icon: "🇬🇧",
    tier: 2,
    ready: true,
    keywords: ["uk to us crochet terms", "crochet term converter", "british crochet terms"],
  },
  {
    slug: "circle-calculator",
    name: "Crochet Circle Round Planner",
    shortName: "Circle Planner",
    description: "Generate a basic staggered-increase circle schedule from a selected stitch preset and round limit; swatch and adjust for the material and stitch.",
    category: "crochet",
    icon: "⭕",
    tier: 2,
    ready: true,
    keywords: ["crochet circle pattern", "flat circle calculator", "crochet circle increases"],
  },
  {
    slug: "needle-guide",
    name: "Sewing \& Craft Needle Guide",
    shortName: "Needle Guide",
    description: "Compare the included needle types, then verify the choice for the specific material and task.",
    category: "both",
    icon: "🪡",
    tier: 2,
    ready: true,
    keywords: ["sewing needle types", "tapestry vs chenille", "needle guide"],
  },
  {
    slug: "amigurumi-shapes",
    name: "Crochet Sphere Calculator & Amigurumi Shapes",
    shortName: "Amigurumi Shapes",
    description: "Generate bounded arithmetic round schedules for basic sphere, cone, cylinder, and oval starting shapes; verify technique and counts before use.",
    category: "crochet",
    icon: "🧸",
    tier: 2,
    ready: true,
    keywords: ["amigurumi shapes", "crochet sphere pattern", "amigurumi basic shapes"],
  },
  {
    slug: "wpi-calculator",
    name: "WPI to Yarn Weight Converter",
    shortName: "WPI Calculator",
    description: "Enter your wraps per inch and instantly identify yarn weight, recommended needles and hooks, gauge range, and suggested projects.",
    category: "both",
    icon: "📏",
    tier: 2,
    ready: true,
    keywords: ["wraps per inch", "WPI calculator", "yarn weight identifier", "unknown yarn weight"],
  },
  {
    slug: "c2c-calculator",
    name: "C2C Blanket Calculator",
    shortName: "C2C Calculator",
    description: "Round entered dimensions to a bounded nominal C2C grid from a two-axis swatch, with optional measured yarn-per-block planning arithmetic.",
    category: "crochet",
    icon: "🔷",
    tier: 2,
    ready: true,
    keywords: ["C2C calculator", "corner to corner crochet", "C2C blanket planner", "diagonal crochet calculator"],
  },
  {
    slug: "cast-on-calculator",
    name: "Cast On Calculator",
    shortName: "Cast On Calc",
    description: "Calculate a rounded cast-on count for an entered width and gauge, with optional pattern-multiple and edge-stitch adjustments.",
    category: "knitting",
    icon: "🧷",
    tier: 2,
    ready: true,
    keywords: ["cast on calculator", "how many stitches to cast on", "knitting cast on count"],
  },
  {
    slug: "hat-calculator",
    name: "Hat Size Calculator",
    shortName: "Hat Calculator",
    description: "Calculate a rounded cast-on count and bounded eight-section crown schedule from the entered head measurement, ease, and gauge.",
    category: "knitting",
    icon: "🧢",
    tier: 2,
    ready: true,
    keywords: ["hat calculator", "knit hat size chart", "knitted crown calculator", "crown decrease calculator"],
  },
  {
    slug: "sock-calculator",
    name: "Sock Circumference Stitch Calculator",
    shortName: "Sock Calculator",
    description: "Calculate a bounded circular stitch-count checkpoint from entered foot circumference, ease, measured gauge, and stitch multiple.",
    category: "knitting",
    icon: "🧦",
    tier: 2,
    ready: true,
    keywords: ["sock calculator", "sock knitting calculator", "sock circumference", "sock stitch count"],
  },
  {
    slug: "granny-square-planner",
    name: "Granny Square Planner",
    shortName: "Granny Planner",
    description: "Plan a nominal granny-square grid, square count, equal-share color average, and unique internal seam length from entered dimensions.",
    category: "crochet",
    icon: "🟩",
    tier: 2,
    ready: true,
    keywords: ["granny square calculator", "granny square blanket planner", "how many granny squares"],
  },
  {
    slug: "sleeve-calculator",
    name: "Sleeve Shaping Calculator",
    shortName: "Sleeve Calculator",
    description: "Plan a bounded paired-decrease sleeve taper from entered measurements and gauge; unsupported odd or over-dense schedules are declined.",
    category: "both",
    icon: "💪",
    tier: 2,
    ready: true,
    keywords: ["sleeve shaping calculator", "sleeve decrease calculator", "tapered sleeve knitting"],
  },
  {
    slug: "raglan-calculator",
    name: "Raglan Body Stitch Checkpoint",
    shortName: "Raglan Checkpoint",
    description: "Calculate one bounded finished-body stitch checkpoint from entered circumference, measured gauge, and stitch multiple.",
    category: "both",
    icon: "👕",
    tier: 2,
    ready: true,
    keywords: ["raglan calculator", "top down raglan calculator", "raglan sweater calculator"],
  },
  {
    slug: "blocking-calculator",
    name: "Blocking Dimension Change Calculator",
    shortName: "Blocking Calc",
    description: "Calculate the signed percentage change between current and requested project dimensions.",
    category: "both",
    icon: "📌",
    tier: 2,
    ready: true,
    keywords: ["blocking calculator", "blocking dimension change", "blocking swatch"],
  },
  {
    slug: "stash-estimator",
    name: "Yarn Stash Estimator",
    shortName: "Stash Estimator",
    description: "Estimate remaining yardage in partial skeins by weight, plus a yardage reference table for unlabeled yarn by weight category.",
    category: "both",
    icon: "🗄️",
    tier: 2,
    ready: true,
    keywords: ["yarn stash calculator", "partial skein yardage", "how much yarn is left", "yarn weight yardage chart"],
  },
  {
    slug: "vintage-pattern-decoder",
    name: "Vintage Pattern Decoder",
    shortName: "Pattern Decoder",
    description: "Translate vintage and UK knitting and crochet patterns into modern US terminology. Converts UK-to-US stitch names, archaic abbreviations, and flags era-specific measurements.",
    category: "both",
    icon: "📜",
    tier: 1,
    ready: true,
    keywords: ["vintage pattern decoder", "UK to US crochet conversion", "old crochet abbreviations", "vintage knitting pattern translator", "translate vintage pattern"],
  },
];

/** Hand-curated related tool mappings for targeted internal linking. */
const relatedToolMap: Record<string, string[]> = {
  "yarn-calculator": ["yarn-weight-chart", "blanket-calculator", "project-cost-calculator", "gauge-calculator"],
  "needle-converter": ["needle-guide", "uk-to-us-converter", "gauge-calculator"],
  "gauge-calculator": ["yarn-calculator", "stitch-pattern-calculator", "blanket-calculator"],
  "yarn-weight-chart": ["fabric-substitute", "yarn-calculator", "needle-converter", "project-cost-calculator"],
  "fabric-substitute": ["yarn-weight-chart", "project-cost-calculator", "needle-guide", "blocking-calculator"],
  "stitch-counter": ["increase-decrease-calculator", "stitch-pattern-calculator", "stitch-quick-reference"],
  "blanket-calculator": ["cast-on-calculator", "yarn-calculator", "gauge-calculator", "stitch-pattern-calculator"],
  "increase-decrease-calculator": ["gauge-calculator", "stitch-counter", "circle-calculator"],
  "stripe-generator": ["color-pooling-calculator", "blanket-calculator", "yarn-calculator"],
  "abbreviation-glossary": ["uk-to-us-converter", "stitch-quick-reference", "needle-converter"],
  "spinning-ratio-calculator": ["yarn-weight-chart", "yarn-calculator", "weaving-sett-calculator"],
  "stitch-pattern-calculator": ["blanket-calculator", "gauge-calculator", "stitch-quick-reference"],
  "stitch-quick-reference": ["abbreviation-glossary", "stitch-counter", "stitch-pattern-calculator"],
  "uk-to-us-converter": ["abbreviation-glossary", "stitch-quick-reference", "needle-converter"],
  "circle-calculator": ["amigurumi-shapes", "increase-decrease-calculator", "blanket-calculator"],
  "needle-guide": ["needle-converter", "cross-stitch-calculator", "thread-converter"],
  "amigurumi-pattern-checker": ["amigurumi-shapes", "circle-calculator", "increase-decrease-calculator", "stitch-quick-reference"],
  "amigurumi-shapes": ["amigurumi-pattern-checker", "circle-calculator", "yarn-calculator", "increase-decrease-calculator"],
  "cross-stitch-calculator": ["thread-converter", "needle-guide", "gauge-calculator"],
  "weaving-sett-calculator": ["spinning-ratio-calculator", "yarn-weight-chart", "stripe-generator"],
  "project-cost-calculator": ["yarn-calculator", "blanket-calculator", "yarn-weight-chart"],
  "color-pooling-calculator": ["stripe-generator", "yarn-calculator", "gauge-calculator"],
  "thread-converter": ["cross-stitch-calculator", "needle-guide", "abbreviation-glossary"],
  "wpi-calculator": ["yarn-weight-chart", "needle-converter", "gauge-calculator", "stash-estimator"],
  "c2c-calculator": ["blanket-calculator", "yarn-calculator", "gauge-calculator", "granny-square-planner"],
  "cast-on-calculator": ["gauge-calculator", "blanket-calculator", "hat-calculator", "stitch-pattern-calculator"],
  "hat-calculator": ["sock-calculator", "gauge-calculator", "yarn-calculator", "cast-on-calculator"],
  "sock-calculator": ["hat-calculator", "gauge-calculator", "yarn-calculator", "needle-converter"],
  "granny-square-planner": ["c2c-calculator", "blanket-calculator", "yarn-calculator", "stripe-generator"],
  "sleeve-calculator": ["raglan-calculator", "increase-decrease-calculator", "gauge-calculator", "yarn-calculator"],
  "raglan-calculator": ["sleeve-calculator", "gauge-calculator", "yarn-calculator", "hat-calculator"],
  "blocking-calculator": ["yarn-weight-chart", "gauge-calculator", "stash-estimator", "wpi-calculator"],
  "stash-estimator": ["yarn-weight-chart", "wpi-calculator", "yarn-calculator", "project-cost-calculator"],
  "vintage-pattern-decoder": ["uk-to-us-converter", "abbreviation-glossary", "stitch-quick-reference", "needle-converter"],
};

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((t) => t.slug === slug);
}

export function getRelatedTools(slug: string, count = 4): Tool[] {
  const mapped = relatedToolMap[slug];
  if (mapped) {
    const result = mapped
      .map((s) => tools.find((t) => t.slug === s))
      .filter((t): t is Tool => t !== undefined)
      .slice(0, count);
    if (result.length > 0) return result;
  }
  // Fallback: score by category and tier
  const current = getToolBySlug(slug);
  if (!current) return tools.slice(0, count);
  return tools
    .filter((t) => t.slug !== slug)
    .sort((a, b) => {
      const aScore =
        (a.category === current.category ? 10 : 0) +
        (a.tier === current.tier ? 5 : 0) +
        (a.ready ? 3 : 0);
      const bScore =
        (b.category === current.category ? 10 : 0) +
        (b.tier === current.tier ? 5 : 0) +
        (b.ready ? 3 : 0);
      return bScore - aScore;
    })
    .slice(0, count);
}
