import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import test from 'node:test';
import ts from 'typescript';
import vm from 'node:vm';
const exports={};vm.runInNewContext(ts.transpileModule(readFileSync('src/lib/guides.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,{exports});
const guides=exports.guides;
const changed=["reading-yarn-labels","knitting-gauge-guide","blanket-yarn-guide","needle-sizes-guide","wpi-guide","pricing-handmade-guide","knitting-sleeve-shaping-guide","yarn-stash-management-guide","cast-on-methods-guide","crochet-stitch-reference-guide","vintage-knitting-patterns"];
const identities=[{"slug":"reading-yarn-labels","title":"The Complete Guide to Reading Yarn Labels (What Every Number Means)","date":"2026-02-23"},{"slug":"knitting-gauge-guide","title":"Knitting Gauge: Why It Matters and How to Get It Right","date":"2026-03-06"},{"slug":"blanket-yarn-guide","title":"How Much Yarn Do You Need for a Blanket?","date":"2026-03-06"},{"slug":"needle-sizes-guide","title":"Knitting Needle Sizes: US, UK, and Metric Explained","date":"2026-03-06"},{"slug":"uk-us-crochet-terms-guide","title":"UK vs US Crochet Terms: Key Conversion Guide","date":"2026-03-06"},{"slug":"wpi-guide","title":"What is WPI (Wraps Per Inch) and How to Measure It","date":"2026-03-06"},{"slug":"pricing-handmade-guide","title":"How to Price Your Handmade Knitting and Crochet","date":"2026-03-06"},{"slug":"amigurumi-beginners-guide","title":"Beginner's Guide to Amigurumi: Shapes, Sizes, and Math","date":"2026-03-06"},{"slug":"flat-circle-crochet-guide","title":"How to Crochet a Flat Circle: Increases Explained","date":"2026-03-11"},{"slug":"sewing-craft-needle-guide","title":"Sewing & Craft Needle Types: Complete Guide","date":"2026-03-11"},{"slug":"knit-crochet-hat-sizing-guide","title":"Hat Sizing Guide: Head Measurements & Crown Shaping","date":"2026-03-11"},{"slug":"knitting-socks-sizing-guide","title":"Knitting Socks: Sizing, Fit & Construction Basics","date":"2026-03-11"},{"slug":"knitting-sleeve-shaping-guide","title":"Knitting Sleeve Shaping: Tapers & Decreases","date":"2026-03-11"},{"slug":"raglan-sweater-guide","title":"Top-Down Raglan Sweaters: Construction Guide","date":"2026-03-11"},{"slug":"blocking-fiber-guide","title":"How to Plan Blocking: Care Instructions and Swatch Tests","date":"2026-03-11"},{"slug":"yarn-stash-management-guide","title":"Yarn Stash Management: Estimating & Organizing","date":"2026-03-11"},{"slug":"c2c-crochet-guide","title":"Corner-to-Corner Crochet (C2C): Beginner Guide","date":"2026-03-11"},{"slug":"granny-square-blanket-guide","title":"Granny Square Blankets: Measured Grid & Joining Plan","date":"2026-08-29"},{"slug":"cast-on-methods-guide","title":"Knitting Cast-On Methods: Which One to Use","date":"2026-03-11"},{"slug":"crochet-stitch-reference-guide","title":"Crochet Stitch Reference: Visual Guide for Beginners","date":"2026-03-11"},{"slug":"yarn-stripe-patterns-guide","title":"Yarn Stripe Patterns: Color Planning & Yarn Tips","date":"2026-03-11"},{"slug":"vintage-knitting-patterns","title":"How to Read and Decode Vintage Knitting Patterns","date":"2026-03-14"},{"slug":"fiber-content-guide","title":"Understanding Fiber Content: A Complete Guide to Yarn Fibers","date":"2026-03-14"}];
test('materially corrected guides retain publication identity and record actual modification date',()=>{
 assert.equal(guides.length,identities.length);for(const prior of identities){const current=guides.find(g=>g.slug===prior.slug);assert.ok(current);assert.equal(current.title,prior.title);assert.equal(current.date,prior.date);if(changed.includes(prior.slug))assert.equal(current.modifiedDate,['knitting-gauge-guide','blanket-yarn-guide','yarn-stash-management-guide','cast-on-methods-guide'].includes(prior.slug)?'2026-09-16':'2026-09-05',prior.slug);else assert.equal(current.modifiedDate,undefined,prior.slug+' not refreshed');}
});
test('changed tool pages existing visible and metadata dates agree with correction date',()=>{
 for(const slug of ["amigurumi-pattern-checker","blanket-calculator","cast-on-calculator","gauge-calculator","needle-converter","project-cost-calculator","sock-calculator","spinning-ratio-calculator","stash-estimator","stitch-counter","thread-converter","weaving-sett-calculator","wpi-calculator","yarn-weight-calculator","blocking-calculator","c2c-calculator","circle-calculator","granny-square-planner","sleeve-calculator"]){const source=readFileSync('src/app/'+slug+'/page.tsx','utf8');assert.match(source,/(?:lastUpdated="|dateModified: "|dateTime=")2026-09-05/,slug+' retains a correction-date field');for(const match of source.matchAll(/(?:lastUpdated="|dateModified: ")(\d{4}-\d{2}-\d{2})/g))assert.equal(match[1],'2026-09-05',slug);if(slug==='yarn-weight-calculator'){assert.doesNotMatch(source,/May 1, 2026|2026-05-01/);assert.match(source,/Last updated: September 5, 2026/);assert.match(source,/dateTime="2026-09-05"/);}}
});
