import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import test from 'node:test';
import ts from 'typescript';
import vm from 'node:vm';
const exports={};vm.runInNewContext(ts.transpileModule(readFileSync('src/lib/guides.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,{exports});
const guides=exports.guides;
const modifiedDates={"reading-yarn-labels":"2026-09-05","knitting-gauge-guide":"2026-09-16","blanket-yarn-guide":"2026-09-16","needle-sizes-guide":"2026-09-05","wpi-guide":"2026-09-05","pricing-handmade-guide":"2026-09-05","knitting-sleeve-shaping-guide":"2026-09-05","yarn-stash-management-guide":"2026-09-16","granny-square-blanket-guide":"2026-09-25","cast-on-methods-guide":"2026-09-16","crochet-stitch-reference-guide":"2026-09-05","vintage-knitting-patterns":"2026-09-05"};
const identities=[{"slug":"reading-yarn-labels","title":"How to Read a Yarn Label: Weight, Gauge & Care","date":"2026-02-23"},{"slug":"knitting-gauge-guide","title":"Knitting Gauge Guide: Swatches, Stitches & Rows","date":"2026-03-06"},{"slug":"blanket-yarn-guide","title":"How Much Yarn for a Blanket? Swatch-Based Guide","date":"2026-03-06"},{"slug":"needle-sizes-guide","title":"Knitting Needle Sizes: US, UK & Metric Chart","date":"2026-03-06"},{"slug":"uk-us-crochet-terms-guide","title":"UK vs US Crochet Terms: Conversion Guide","date":"2026-03-06"},{"slug":"wpi-guide","title":"WPI Guide: How to Measure Wraps Per Inch","date":"2026-03-06"},{"slug":"pricing-handmade-guide","title":"How to Price Handmade Knitting & Crochet","date":"2026-03-06"},{"slug":"amigurumi-beginners-guide","title":"Amigurumi for Beginners: Shapes, Counts & Math","date":"2026-03-06"},{"slug":"flat-circle-crochet-guide","title":"Crochet Flat Circle Guide: Increases & Shape Fixes","date":"2026-03-11"},{"slug":"sewing-craft-needle-guide","title":"Sewing Needle Types & Sizes: Craft Guide","date":"2026-03-11"},{"slug":"knit-crochet-hat-sizing-guide","title":"Knit Hat Sizing Guide: Gauge, Ease & Crown Shaping","date":"2026-03-11"},{"slug":"knitting-socks-sizing-guide","title":"Knitting Socks: Sizing, Fit & Construction","date":"2026-03-11"},{"slug":"knitting-sleeve-shaping-guide","title":"Knitting Sleeve Shaping: Tapers & Decreases","date":"2026-03-11"},{"slug":"raglan-sweater-guide","title":"Top-Down Raglan Sweater Construction Guide","date":"2026-03-11"},{"slug":"blocking-fiber-guide","title":"Blocking Knitting & Crochet: Swatch Test Guide","date":"2026-03-11"},{"slug":"yarn-stash-management-guide","title":"Yarn Stash Guide: Estimate Partial-Skein Yardage","date":"2026-03-11"},{"slug":"c2c-crochet-guide","title":"Corner-to-Corner Crochet Guide: C2C Blocks & Gauge","date":"2026-03-11"},{"slug":"granny-square-blanket-guide","title":"Granny Square Blanket Guide: Squares, Yarn & Joining","date":"2026-08-29"},{"slug":"cast-on-methods-guide","title":"Knitting Cast-On Guide: Gauge, Width & Repeats","date":"2026-03-11"},{"slug":"crochet-stitch-reference-guide","title":"Crochet Stitch Reference: Basic Stitches & Terms","date":"2026-03-11"},{"slug":"yarn-stripe-patterns-guide","title":"Yarn Stripe Pattern Guide: Rows, Color & Yardage","date":"2026-03-11"},{"slug":"vintage-knitting-patterns","title":"Vintage Knitting Patterns: Terms, Gauge & Sizing","date":"2026-03-14"},{"slug":"fiber-content-guide","title":"Yarn Fiber Types: Wool, Cotton, Acrylic & Blends","date":"2026-03-14"}];
test('guide search titles retain publication slugs and dates and record actual modification dates',()=>{
 assert.equal(guides.length,identities.length);for(const prior of identities){const current=guides.find(g=>g.slug===prior.slug);assert.ok(current);assert.equal(current.title,prior.title);assert.equal(current.date,prior.date);assert.equal(current.modifiedDate,modifiedDates[prior.slug],prior.slug);}
});
test('changed tool pages existing visible and metadata dates agree with correction date',()=>{
 for(const slug of ["amigurumi-pattern-checker","blanket-calculator","cast-on-calculator","gauge-calculator","needle-converter","project-cost-calculator","sock-calculator","spinning-ratio-calculator","stash-estimator","stitch-counter","thread-converter","weaving-sett-calculator","wpi-calculator","yarn-weight-calculator","blocking-calculator","c2c-calculator","circle-calculator","granny-square-planner","sleeve-calculator"]){const expectedDate=slug==='blanket-calculator'?'2026-09-16':'2026-09-05';const source=readFileSync('src/app/'+slug+'/page.tsx','utf8');assert.match(source,/(?:lastUpdated="|dateModified: "|dateTime=")\d{4}-\d{2}-\d{2}/,slug+' retains a correction-date field');for(const match of source.matchAll(/(?:lastUpdated="|dateModified: ")(\d{4}-\d{2}-\d{2})/g))assert.equal(match[1],expectedDate,slug);if(slug==='yarn-weight-calculator'){assert.doesNotMatch(source,/May 1, 2026|2026-05-01/);assert.match(source,/Last updated: September 5, 2026/);assert.match(source,/dateTime="2026-09-05"/);}}
});
